<?php
/**
 * KrishTechnolabs
 *
 * PHP version 7
 *
 * @category  KrishTechnolabs
 * @package   Ktpl_ElasticSearch
 * @author    Dhara Bhatti <dhara.bhatti@krishtechnolabs.com>
 * @copyright 2019 (c) KrishTechnolabs (https://www.KrishTechnolabs.com/)
 * @license   https://www.krishtechnolabs.com/LICENSE.txt Krish License
 * @link      https://www.krishtechnolabs.com/
 */
?>

<?php if ($this->isEnabled()): ?>
<script type="application/ld+json">
{
   "@context": "http://schema.org",
   "@type": "WebSite",
   "url": "<?= $block->getBaseUrl() ?>",
   "potentialAction": {
     "@type": "SearchAction",
     "target": "<?= urldecode($block->getTargetUrl()) ?>",
     "query-input": "required name=search_term_string"
   }
}
</script>
<?php endif ?>