    <div class="carousel-container">
        <div id="homecateslider1" class="owl-carousel owl-theme">
            <div class="item">
                <img src="<?php echo $this->getViewFileUrl('images/cate-img01.jpg'); ?>" alt="">
                <p><a href="#">Mobiles</a></p>
            </div>
            <div class="item">
                <img src="<?php echo $this->getViewFileUrl('images/cate-img01.jpg'); ?>" alt="">
                <p><a href="#">Mobiles</a></p>
            </div>
            <div class="item">
                <img src="<?php echo $this->getViewFileUrl('images/cate-img01.jpg'); ?>" alt="">
                <p><a href="#">Mobiles</a></p>
            </div>
            <div class="item">
                <img src="<?php echo $this->getViewFileUrl('images/cate-img01.jpg'); ?>" alt="">
                <p><a href="#">Mobiles</a></p>
            </div>
            <div class="item">
                <img src="<?php echo $this->getViewFileUrl('images/cate-img01.jpg'); ?>" alt="">
                <p><a href="#">Mobiles</a></p>
            </div>
            <div class="item">
                <img src="<?php echo $this->getViewFileUrl('images/cate-img01.jpg'); ?>" alt="">
                <p><a href="#">Mobiles</a></p>
            </div>
            <div class="item">
                <img src="<?php echo $this->getViewFileUrl('images/cate-img01.jpg'); ?>" alt="">
                <p><a href="#">Mobiles</a></p>
            </div>
            <div class="item">
                <img src="<?php echo $this->getViewFileUrl('images/cate-img01.jpg'); ?>" alt="">
                <p><a href="#">Mobiles</a></p>
            </div>
            <div class="item">
                <img src="<?php echo $this->getViewFileUrl('images/cate-img01.jpg'); ?>" alt="">
                <p><a href="#">Mobiles</a></p>
            </div>
            <div class="item">
                <img src="<?php echo $this->getViewFileUrl('images/cate-img01.jpg'); ?>" alt="">
                <p><a href="#">Mobiles</a></p>
            </div>
        </div>
    </div>



<script type="text/javascript">
         require(["jquery","owlcarousel"],function($) {
           $(document).ready(function () {
                $("#homecateslider1").owlCarousel({
                autoPlay: 3000, //3000 Set AutoPlay to 3 seconds
                margin:50,
                items : 8,
                navigation : false,
                nav: true,
                loop:false,
                rtl:true,
                responsive:{
                    0:{
                        items:1
                    },
                    600:{
                        items:3
                    },
                    1000:{
                        items:5
                    },
                    1200:{
                        items:8
                    }
                }
          });
    });
});
</script>