<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Sales
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>

<?= /* @escapeNotVerified */ $block->getItem()->getName() ?>
<div><strong><?= /* @escapeNotVerified */ __('SKU') ?>:</strong> <?= implode('<br />', $this->helper('Magento\Catalog\Helper\Data')->splitSku($block->escapeHtml($block->getItem()->getSku()))); ?></div>
<?php if ($block->getOrderOptions()) : ?>
    <ul class="item-options">
    <?php foreach ($block->getOrderOptions() as $option) : ?>
        <li><strong><?= /* @escapeNotVerified */ $option['label'] ?>:</strong><br />
        <?php if (is_array($option['value'])) : ?>
            <?php foreach ($option['value'] as $item) : ?>
                <?= $block->getValueHtml($item) ?><br />
            <?php endforeach; ?>
        <?php else : ?>
            <?= $block->escapeHtml($option['value']); ?>
        <?php endif; ?>
        </li>
    <?php endforeach; ?>
    </ul>
<?php endif; ?>
<?= $block->escapeHtml($block->getItem()->getDescription()) ?>
