<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Catalog
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
/** @var $block \Magedelight\Catalog\Block\Adminhtml\Attribute\Edit\Options\Placeholder  */
?>

<div class="fieldset-wrapper admin__collapsible-block-wrapper opened" id="manage-placeholders-wrapper">
    <div class="fieldset-wrapper-placeholder">
        <strong class="admin__collapsible-placeholder" data-toggle="collapse" data-target="#manage-placeholders-content">
            <span><?= __('Manage Placeholders') ?></span>
        </strong>
    </div>
    <div class="fieldset-wrapper-content in collapse" id="manage-placeholders-content">
        <fieldset class="fieldset">
            <div>
                <?php $_placeholders = $block->getPlaceholderValues() ?>
                <?php foreach ($block->getStores() as $_store): ?>
                    <div class="field admin__field">
                        <label class="admin__field-label label">
                            <?= $_store->getName() ?>
                        </label>
                        <div class="control admin__field-control">
                            <textarea class="admin__control-textarea<?php if ($_store->getId() == \Magento\Store\Model\Store::DEFAULT_STORE_ID):
                                ?> required-option<?php
                                                                    endif; ?>"
                                      name="attribute_placeholder[<?= $_store->getId() ?>]"
                                      rows="5"
                                      cols="25"
                                        <?php if ($block->getReadOnly()):
                                            ?> disabled="disabled"<?php
                                        endif;?>><?= $block->escapeHtml($_placeholders[$_store->getId()]) ?></textarea>
                        </div>
                    </div>
                <?php endforeach; ?>
            </div>
        </fieldset>
    </div>
</div>
