<?php
/**
 * @category   CAT
 * @package    CAT_OfferPage
 * @author     mohd.salman0306@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace CAT\OfferPage\Controller\Index;

use Magento\Framework\App\Action\Context;
use Magento\Framework\Exception\NotFoundException;
use CAT\OfferPage\Block\OfferPageView;

class View extends \Magento\Framework\App\Action\Action
{
	protected $_offerpageview;

	public function __construct(
        Context $context,
        OfferPageView $offerpageview
    ) {
        $this->_offerpageview = $offerpageview;
        parent::__construct($context);
    }

	public function execute()
    {
    	if(!$this->_offerpageview->getSingleData()){
    		throw new NotFoundException(__('Parameter is incorrect.'));
    	}
    	
        $this->_view->loadLayout();
        $this->_view->getLayout()->initMessages();
        $this->_view->renderLayout();
    }
}
