<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Commissions
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
/* @codingStandardsIgnoreFile */
/** @var $block Magedelight\Commissions\Block\Transaction\Grid */
$collection = $block->getCollection();
$om = \Magento\Framework\App\ObjectManager::getInstance();
$session = $om->get('Magento\Customer\Model\Session');
$gridsession = $session->getGridSession();
$financial_transaction_summary = $gridsession['grid_session']['financial_transaction_summary'];
?>
<form method="get" action="<?= $block->getSubmitUrl() ?>" id="vendor-transaction-search" name="vendor_transaction_search">
    <div class="row commission-list">
        <div class="row-gutter toolbar-wrapper mb10">
            <div class="col-xs-4">
                <input type="hidden" name="tab" value="<?= $this->getRequest()->getParam('tab',
                                                                                                 '3,0') ?>">            
                <input id="sort-order" type="hidden" name="sort_order" value="<?= $this->getRequest()->getParam('sort_order',
                                                                                                                        'created_at') ?>">
                <input id="sort-direction" type="hidden" name="dir" value="<?= $this->getRequest()->getParam('dir',
                                                                                                                     'DESC') ?>">    
                <div class="block block-search">
                    <div class="content">
                        <div class="field search-catalog">
                            <div class="control">
                                <input placeholder="<?= __('Search...') ?>" type="text" value="<?php
                                if ($this->getRequest()->getParam('q')) {
                                    echo $this->getRequest()->getParam('q');
                                } elseif ($financial_transaction_summary['q']) {
                                    echo $financial_transaction_summary['q'];
                                }
                                ?>" name="q" id="vendor_order_search" class="input-text vendor search-order-input">
                            </div>
                            <div class="actions">
                                <div class="vendor primary"><button type="submit" class="vendor action login primary"><span>Search</span></button></div>
                            </div>
                        </div>
                    </div>
                </div>            
            </div>
<div class="col-xs-8">
    <div class="row">
        <div class="col-xs-3 pt10">
             <a rel="new" href="javascript:void(0)" class="action-reset search"><?= __('Reset') ?></a>
        </div>
         <div class="col-xs-9">
                <div class="toolbar-filter-wrapper">
                    <div class="data-grid-filters-action-wrap">
                        <span class="clear-filters"><a rel="new" href="javascript:void(0)" class="action action-reset filter"><?= __('Clear') ?></a></span>
                        <button class="action secondary action-default _active" type="button" data-action="grid-filter-expand" title="Filters">
                            <span><?= __('Filters') ?></span>
                        </button>
                    </div>
                   
                <div class="data-grid-filters-actions-wrap">
                        <div class="data-grid-filters-action-wrap">
                            <a class="action primary export" href="<?= $block->getUrl('*/*/exportPost',
                             ['_current' => true]) ?>">Export</a>
                        </div>
                    </div>
                </div>
          </div>
    </div>
</div>
</div>
    </div>
    <div class="filter-wrapper" style="display:none;">
        <fieldset class="row fieldset">
            <div class="row-gutter filter-row">
                <div class="col-md-6 col-lg-3 filter-section">
                    <fieldset class="fieldset">
                        <legend class="legend">
                            <span class=""><?= __('Commission') ?></span>
                        </legend>
                        <div class="field">
                            <label class="label" for="commission_from">
                                <span><?= __('from') ?></span>
                            </label>
                            <div class="control">
                                <input class="input-text" 
                                       type="text"  
                                       name="commission[from]"
                                       id="commission_from" 
                                       value="<?php
                                       if ($this->getRequest()->getParam('commission')['from']) {
                                           echo $this->getRequest()->getParam('commission')['from'];
                                       } elseif ($financial_transaction_summary['commision[from]']) {
                                           echo $financial_transaction_summary['commision[from]'];
                                       }
                                       ?>">
                            </div>
                        </div>
                        <div class="field">
                            <label class="label" for="commission_to">
                                <span><?= __('to') ?></span>
                            </label>
                            <div class="control">
                                <input class="input-text" 
                                       type="text"  
                                       name="commission[to]"                                        
                                       id="commission_to" 
                                       value="<?php
                                       if ($this->getRequest()->getParam('commission')['to']) {
                                           echo $this->getRequest()->getParam('commission')['to'];
                                       } elseif ($financial_transaction_summary['commision[to]']) {
                                           echo $financial_transaction_summary['commision[to]'];
                                       }
                                       ?>">
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="col-md-6 col-lg-3 filter-section">
                    <fieldset class="fieldset">
                        <legend class="legend">
                            <span class=""><?= __('Marketplace Fee') ?></span>
                        </legend>
                        <div class="field">
                            <label class="label" for="marketplace_fee_from">
                                <span><?= __('from') ?></span>
                            </label>
                            <div class="control">
                                <input class="input-text" 
                                       type="text"  
                                       name="marketplace_fee[from]"
                                       id="marketplace_fee_from" 
                                       value="<?php
                                       if ($this->getRequest()->getParam('marketplace_fee')['from']) {
                                           echo $this->getRequest()->getParam('marketplace_fee')['from'];
                                       } elseif ($financial_transaction_summary['marketplace_fee[from]']) {
                                           echo $financial_transaction_summary['marketplace_fee[from]'];
                                       }
                                       ?>">
                            </div>
                        </div>
                        <div class="field">
                            <label class="label" for="marketplace_fee_to">
                                <span><?= __('to') ?></span>
                            </label>
                            <div class="control">
                                <input class="input-text" 
                                       type="text"  
                                       name="marketplace_fee[to]"                                        
                                       id="marketplace_fee_to" 
                                       value="<?php
                                       if ($this->getRequest()->getParam('marketplace_fee')['to']) {
                                           echo $this->getRequest()->getParam('marketplace_fee')['to'];
                                       } elseif ($financial_transaction_summary['marketplace_fee[to]']) {
                                           echo $financial_transaction_summary['marketplace_fee[to]'];
                                       }
                                       ?>">
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="col-md-6 col-lg-3 filter-section">
                    <fieldset class="fieldset">
                        <legend class="legend">
                            <span class=""><?= __('Cancellation Fee') ?></span>
                        </legend>
                        <div class="field">
                            <label class="label" for="">
                                <span><?= __('from') ?></span>
                            </label>
                            <div class="control">
                                <input class="input-text" 
                                       type="text"  
                                       name="cancellation_fee[from]"
                                       id="cancellation_fee_from" 
                                       value="<?php
                                       if ($this->getRequest()->getParam('cancellation_fee')['from']) {
                                           echo $this->getRequest()->getParam('cancellation_fee')['from'];
                                       } elseif ($financial_transaction_summary['cf[from]']) {
                                           echo $financial_transaction_summary['cf[from]'];
                                       }
                                       ?>">
                            </div>
                        </div>
                        <div class="field">
                            <label class="label" for="cancellation_fee_to">
                                <span><?= __('to') ?></span>
                            </label>
                            <div class="control">
                                <input class="input-text" 
                                       type="text"  
                                       name="cancellation_fee[to]"                                        
                                       id="cancellation_fee_to" 
                                       value="<?php
                                       if ($this->getRequest()->getParam('cancellation_fee')['to']) {
                                           echo $this->getRequest()->getParam('cancellation_fee')['to'];
                                       } elseif ($financial_transaction_summary['cf[to]']) {
                                           echo $financial_transaction_summary['cf[to]'];
                                       }
                                       ?>">
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="col-md-6 col-lg-3 filter-section">
                    <fieldset class="fieldset">
                        <legend class="legend">
                            <span class=""><?= __('Service Tax') ?></span>
                        </legend>
                        <div class="field">
                            <label class="label" for="service_tax_from">
                                <span><?= __('from') ?></span>
                            </label>
                            <div class="control">
                                <input class="input-text" 
                                       type="text"  
                                       name="service_tax[from]"
                                       id="service_tax_from" 
                                       value="<?php
                                       if ($this->getRequest()->getParam('service_tax')['from']) {
                                           echo $this->getRequest()->getParam('service_tax')['from'];
                                       } elseif ($financial_transaction_summary['service_tax[from]']) {
                                           echo $financial_transaction_summary['service_tax[from]'];
                                       }
                                       ?>">
                            </div>
                        </div>
                        <div class="field">
                            <label class="label" for="service_tax_to">
                                <span><?= __('to') ?></span>
                            </label>
                            <div class="control">
                                <input class="input-text" 
                                       type="text"  
                                       name="service_tax[to]"                                        
                                       id="service_tax_to" 
                                       value="<?php
                                       if ($this->getRequest()->getParam('service_tax')['to']) {
                                           echo $this->getRequest()->getParam('service_tax')['to'];
                                       } elseif ($financial_transaction_summary['service_tax[to]']) {
                                           echo $financial_transaction_summary['service_tax[to]'];
                                       }
                                       ?>">
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
             <div class="row-gutter filter-row">
                <div class="col-md-6 col-lg-3 filter-section">
                    <fieldset class="fieldset">
                        <legend class="legend">
                            <span class=""><?= __('Net Payable') ?></span>
                        </legend>
                        <div class="field">
                            <label class="label" for="total_amount_from">
                                <span><?= __('from') ?></span>
                            </label>
                            <div class="control">
                                <input class="input-text" 
                                       type="text"  
                                       name="total_amount[from]"  
                                       id="total_amount_from" 
                                       value="<?php
                                       if ($this->getRequest()->getParam('total_amount')['from']) {
                                           echo $this->getRequest()->getParam('total_amount')['from'];
                                       } elseif ($financial_transaction_summary['net_payable[from]']) {
                                           echo $financial_transaction_summary['net_payable[from]'];
                                       }
                                       ?>">
                            </div>
                        </div>
                        <div class="field">
                            <label class="label" for="total_amount_to">
                                <span><?= __('to') ?></span>
                            </label>
                            <div class="control">
                                <input class="input-text" 
                                       type="text"  
                                       name="total_amount[to]"  
                                       id="total_amount_to" 
                                       value="<?php
                                       if ($this->getRequest()->getParam('total_amount')['to']) {
                                           echo $this->getRequest()->getParam('total_amount')['to'];
                                       } elseif ($financial_transaction_summary['net_payable[to]']) {
                                           echo $financial_transaction_summary['net_payable[to]'];
                                       }
                                       ?>">
                            </div>
                        </div>
                    </fieldset>
                </div>                
                <div class="col-md-6 col-lg-3 filter-section">
                    <fieldset class="fieldset" id="created_date_range">
                        <legend class="legend">
                            <span class=""><?= __('Created Date') ?></span>
                        </legend>
                        <div class="field">
                            <label class="label" for="created_date_from">
                                <span><?= __('from') ?></span>
                            </label>
                            <div class="control date-control date-field-container">
                                <input class="input-text" 
                                       type="text"  
                                       name="created_at[from]"  
                                       placeholder="MM/DD/YYYY"
                                       readonly="readonly"
                                       id="created_date_from" 
                                       value="<?php
                                       if ($this->getRequest()->getParam('created_at')['from']) {
                                           echo $this->getRequest()->getParam('created_at')['from'];
                                       } elseif ($financial_transaction_summary['created_date[from]']) {
                                           echo $financial_transaction_summary['created_date[from]'];
                                       }
                                       ?>">
                            </div>
                        </div>
                        <div class="field">
                            <label class="label" for="created_date_to">
                                <span><?= __('to') ?></span>
                            </label>
                            <div class="control date-control date-field-container">
                                <input class="input-text" 
                                       type="text"  
                                       name="created_at[to]"  
                                       placeholder="MM/DD/YYYY"
                                       readonly="readonly"
                                       id="created_date_to" 
                                       value="<?php
                                       if ($this->getRequest()->getParam('created_at')['to']) {
                                           echo $this->getRequest()->getParam('created_at')['to'];
                                       } elseif ($financial_transaction_summary['created_date[to]']) {
                                           echo $financial_transaction_summary['created_date[to]'];
                                       }
                                       ?>">
                            </div>
                        </div>
                    </fieldset>
                </div>                
                <div class="col-md-6 col-lg-3 filter-section">
                    <fieldset class="fieldset field-full-width">
                        <legend class="legend">
                            <span class=""><?= __('Order Number') ?></span>
                        </legend>
                        <div class="field">
                            <div class="control">
                                <input class="input-text" type="text" name="order_number" id="order_number" value="<?php
                                       if ($this->getRequest()->getParam('order_number')) {
                                           echo $this->getRequest()->getParam('order_number');
                                       } elseif ($financial_transaction_summary['increment_id']) {
                                           echo $financial_transaction_summary['increment_id'];
                                       }
                                       ?>">
                            </div>
                        </div>
                    </fieldset>
                </div>
                <div class="col-md-6 col-lg-3 filter-section">
                    <fieldset class="fieldset field-full-width">
                        <legend class="legend">
                            <span class=""><?= __('Status') ?></span>
                        </legend>
                        <div class="field">
                            <div class="control">
                                <select class="input-text" name="status" id="status">
                                    <option value=""></option>
                                    <?php
                                    if ($this->getRequest()->getParam('status')) {
                                        $status = $this->getRequest()->getParam('status');
                                    } elseif ($financial_transaction_summary['status']) {
                                        $status = $financial_transaction_summary['status'];
                                    } else {
                                        $status = "";
                                    }

                                    foreach ($block->toOptionArray() as $_item) {
                                        if (!is_null($status) && $status != '') {
                                            $selected = ($_item['value'] == $status) ? 'selected="selected"' : '';
                                        } else {
                                            $selected = '';
                                        }
                                        ?> 
                                        <option <?= $selected ?> value="<?= $_item['value'] ?>"><?= $_item['label'] ?></option>
<?php }
?>
                                </select>                                
                            </div>
                        </div>
                    </fieldset>
                </div>
            </div>
        </fieldset>
        <div class="row">
        <div class="row-gutter">
            <div class="filters-footer col-md-12">
                <div class="action-toolbar main-actions">
                    <button class="action primary grid-filter-cancel cancel" type="reset" data-action="grid-filter-cancel" >
                        <span><?= __('Cancel') ?></span>
                    </button>
                    <button class="action primary" type="submit" data-action="grid-filter-apply" >
                        <span><?= __('Apply') ?></span>
                    </button>
                </div>
            </div>
        </div>
        </div>
    </div>
    <input type="hidden" name="session-clear-transaction" id="session-clear-transaction" value="0"/>
</form>
<div class="table-wrapper rb-transaction-history">
    <table class="data table table-transaction-items rb-table-transaction-items history<?php if($block->isLiable() == false){ echo ' rb-shipping-admin-liable';}?>" id="transaction-table">
        <thead>
            <tr>
                <th scope="col" sortorder="increment_id" class="col id sortable w15"><?= __('Order No#') ?></th>
                <th scope="col" sortorder="transaction_type" class="col  amount sortable w12"><?= __('Transaction Type') ?></th>
                <th scope="col" sortorder="created_at" class="col date sortable w26"><?= __('Created Date') ?></th>
                <th scope="col" sortorder="grand_total" class="col fee sortable"><span>*</span><?= __('Order Value') ?></th>
                <th scope="col" sortorder="rvo.shipping_amount" class="col fee sortable w13"><?= __('Shipping Charges') ?></th>
                <th scope="col" sortorder="total_refunded" class="col fee sortable w13"><?= __('Total Refunded') ?></th>
                <th scope="col" sortorder="total_commission" class="col fee sortable w15"><?= __('Commission') ?></th>
                <th scope="col" sortorder="marketplace_fee" class="col fee sortable"><?= __('Marketplace Fee') ?></th>
                <th scope="col" sortorder="cancellation_fee" class="col fee sortable"><?= __('Cancellation Fee') ?></th>
                <th scope="col" sortorder="service_tax" class="col fee sortable w12"><?= __('Service Tax') ?></th>
                <th scope="col" sortorder="total_amount" class="col  amount sortable w12"><?= __('Net Payable') ?></th>
                <th scope="col" sortorder="status" class="col status sortable text-center"><?= __('Status') ?></th>
                <th scope="col" sortorder="status" class="col status sortable text-center"><?= __('Action') ?></th>
                
            </tr>
        </thead>
        <tbody>  
<?php if ($collection->count()) { ?>
                <?php foreach ($collection as $_item) { ?>
                  <?php if(floatval($_item->getTotalAmount()) < 0){
                            $class = ' col-negative';
                        } elseif(floatval($_item->getTotalAmount()) > 0){
                            $class = ' col-positive';
                        }else{
                            $class = ' col-neutral';
                        } ?>
                    <tr>
                        <td class="col data-grid-id-cell">
                            <div class="data-grid-cell-content">
                                <?= $_item->getIncrementId() ?>
                            </div>
                        </td>
                         <td class="col <?= $class; ?> data-grid-price-cell">
                            <div class="data-grid-cell-content">
                                <span class="value">
                                    <?php echo str_replace("_", ' ', ucwords($_item->getTransactionType(), "_")); ?>
                                </span>
                            </div>
                        </td>                        
                        <td class="col data-grid-date-cell">
                            <div class="data-grid-cell-content">
                                <?= $block->dateFormat($_item->getCreatedAt()) ?>
                            </div>
                        </td>
                        <td class="col fee">
                            <div class="data-grid-cell-content">
                                <?= $block->formatAmount($_item->getGrandTotal(), $_item->getOrderCurrencyCode()) ?>
                            </div>
                        </td>
                        <td class="col<?= (floatval($_item->getShippingAmount()) < 0) ? ' col-negative' : ' col-neutral'?> rb-shipping-charges data-grid-price-cell">
                            <div class="data-grid-cell-content">
                                <span class="value">
                                    <?= $block->formatAmount(abs($_item->getRvoShippingAmount()), $_item->getOrderCurrencyCode()) ?>
                                </span>
                            </div>
                        </td>
                        <td class="col<?= (floatval($_item->getTotalRefunded()) > 0) ? ' col-negative' : ' col-neutral' ?> data-grid-price-cell">
                            <div class="data-grid-cell-content">
                                <span class="value">
                                    <?= $block->formatAmount($_item->getTotalRefunded(), $_item->getOrderCurrencyCode()) ?>
                                </span>
                            </div>
                        </td>
                        <td class="col<?= (floatval($_item->getTotalCommission()) > 0) ? ' col-negative' : ' col-neutral' ?>">
                            <div class="data-grid-cell-content">
                                <span class='value'>
                                    <?= $block->formatAmount($_item->getTotalCommission(), $_item->getOrderCurrencyCode()) ?>
                                </span>
                            </div>
                        </td>                    
                        <td class="col<?= (floatval($_item->getMarketPlaceFee()) > 0) ? ' col-negative' : ' col-neutral' ?>">
                            <div class="data-grid-cell-content">
                                <span class="value">
                                    <?= $block->formatAmount($_item->getMarketPlaceFee(), $_item->getOrderCurrencyCode()) ?>
                                </span>
                            </div>
                        </td>
                        <td class="col<?= (floatval($_item->getCancellationFee()) > 0) ? ' col-negative' : ' col-neutral' ?>">
                            <div class="data-grid-cell-content">
                                <span class="value">
                                    <?= $block->formatAmount($_item->getCancellationFee(), $_item->getOrderCurrencyCode()) ?>
                                </span>
                            </div>
                        </td>
                        <td class="col<?= (floatval($_item->getServiceTax()) > 0) ? ' col-negative' : ' col-neutral' ?>">
                            <div class="data-grid-cell-content">
                                <span class="value">
                                    <?= $block->formatAmount($_item->getServiceTax(), $_item->getOrderCurrencyCode()) ?>
                                </span>
                            </div>
                        </td>
                        <td class="col <?= $class; ?> data-grid-price-cell">
                            <div class="data-grid-cell-content">
                                <span class="value">
                                    <?php 
                                    if($_item->getTotalAmount() < 0){
                                        echo $block->formatAmount($_item->getTotalAmount()*(-1), $_item->getOrderCurrencyCode());
                                    }else{
                                        echo $block->formatAmount($_item->getTotalAmount(), $_item->getOrderCurrencyCode());
                                    } ?>
                                </span>
                            </div>
                        </td>                        
                        <td class="col data-grid-status-cell">
                            <div class="data-grid-cell-content">
                                <span class="status <?= strtolower($block->getStatus($_item->getStatus())) ?>">
                                    <?= $block->getStatus($_item->getStatus()) ?>
                                </span>
                            </div>
                        </td>
                        <td class="col data-grid-status-cell">
                            <a title="<?= __('View') ?>" href="javascript:void(0);" data-transaction_id = "<?= $_item->getVendorPaymentId(); ?>" class="action view"  data-url = "" >
                                <span><?= __('View') ?></span> 
                            </a>
                        </td>
                    </tr>
                    <?php } ?>
                    <?php } else { ?>
                    <tr>
                        <td colspan="12">
                              <div class="message info empty" id="transaction-msg">
                              </div>
                        </td>
                    </tr>
                    <?php } ?>
        </tbody>
    </table>
    <div class="note">
        <span>*</span><b>Note:--</b><?= __('Shipping charges are already included in respective order value.');?>
    </div>
</div>
<?php if ($block->getPagerHtml()): ?>
    <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml(); ?></div>
<?php endif ?>
<div id="popup-modal" style="display: none;"></div>
<script type="text/javascript">
    require(['jquery',
        'mage/calendar', /* Calender widget */
    ], function ($) {
        $(".filter-wrapper").hide();
        $(".action-default").click(function () {
            $(".filter-wrapper").toggle(500);
        });
        $(".grid-filter-clear-all").click(function () {
            $form = $(this).parents('form');
            $(':input:not([type=hidden])', $form).val("");
            $($form).submit();
        });
        $("#created_date_range").dateRange({
            buttonText: "<?= __('Select Date') ?>",
            showOn: "button",
            from: {
                id: "created_date_from"
            },
            to: {
                id: "created_date_to"
            }
        });
        $(document).ready(function () {
            
            /*
             * Sorting feature
             */
            $currentSortOrder = $('#sort-order').val();
            $currentSortDir = $('#sort-direction').val();

            if ($currentSortOrder != null && $currentSortOrder != '') {
                $sortDirClass = ($currentSortDir == 'DESC') ? 'descend' : 'ascend';
                $('th[sortorder="' + $currentSortOrder + '"]').addClass($sortDirClass);
            }
            $sortDir = 'ASC';

            $('#transaction-table .sortable').click(function ($e) {
                $sortOrder = $(this).attr('sortorder');
                if ($currentSortOrder == $sortOrder) {
                    $sortDir = ($currentSortDir == 'DESC') ? 'ASC' : 'DESC';
                }
                $('#sort-order').val($sortOrder); /*for post */
                $('#sort-direction').val($sortDir); /*for post */
                $('#vendor-transaction-search').submit();
            });

            $(".grid-filter-cancel").click(function () {
                $(this).parents('.filter-wrapper').toggle(500);
            });

            $(".action-reset").click(function () {
                $form = $(this).parents('form');
                if ($(this).hasClass('search')) {
                    $parent = $('.block-search', $form);
                } else {
                    $parent = $('.filter-wrapper', $form);
                }
                $(':input:not([type=hidden])', $parent).val("");

                jQuery('#session-clear-transaction').val(1);
                $($form).submit();
            });
            
            
            $value = "false";
                    $('input[type=text]').each(function () {
                        var text_value = $(this).val();
                        if (text_value != '')
                        {
                            $value = "true";
                        }

                    });
                    
                    if (jQuery('#vendor_order_search')[0].value != "" || $value == "true") {
                        jQuery('#transaction-msg').html('<span>Your search result could not find</<span>');
                    } else {
                        jQuery('#transaction-msg').html('<span>We couldn\'t find any records.</<span>');
                    }

             

        });
    });
</script>  
<script>
    require(['jquery', 'transactionview'], function ($, transactionview) {
        $(function() {
          var options = {
                ajaxUrl:'<?= $block->getUrl('rbsales/transaction/view'); ?>',
            };
            transactionview.view(options,'.action.view');
        });
    });
</script>