<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Sales
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<?php  $_order = $block->getCreditmemo()->getOrder() ?>
<?= $block->getChildHtml('rbsales_order_info') ?>
<section class="front__page-section">
    <div class="front__page-section-title">
        <span class="title"><?= /* @escapeNotVerified */ __('Payment &amp; Shipping Method') ?></span>
    </div>
    <div class="front__page-section-content">

        <?php if (!$_order->getIsVirtual()) : ?>
        <div class="front__page-section-item order-payment-method">
        <?php else : ?>
        <div class="front__page-section-item order-payment-method order-payment-method-virtual">
        <?php endif; ?>
            <?php /* Billing Address */?>
            <div class="front__page-section-item-title">
                <span class="title"><?= /* @escapeNotVerified */ __('Payment Information') ?></span>
            </div>
            <div class="front__page-section-item-content">
                <div class="order-payment-method-title"><?= $block->getChildHtml('rbsales_order_payment') ?></div>
                <div class="order-payment-currency"><?= /* @escapeNotVerified */ __('The order was placed using %1.', $_order->getOrderCurrencyCode()) ?></div>
                <div class="order-payment-additional"><?= $block->getChildHtml('rbsales_order_payment_additional'); ?></div>
            </div>
        </div>

        <?php if (!$_order->getIsVirtual()) : ?>
        <div class="front__page-section-item order-shipping-address">
            <?php /* Shipping Address */ ?>
            <div class="front__page-section-item-title">
                <span class="title"><?= /* @escapeNotVerified */ __('Shipping Information') ?></span>
            </div>
            <div class="shipping-description-wrapper front__page-section-item-content">
                <div class="shipping-description-title"><?= $block->escapeHtml($_order->getShippingDescription()) ?></div>
                <div class="shipping-description-content">
                    <?= /* @escapeNotVerified */ __('Total Shipping Charges'); ?>:

                    <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingPriceIncludingTax()) : ?>
                        <?php $_excl = $block->displayShippingPriceInclTax($_order); ?>
                    <?php else : ?>
                        <?php $_excl = $block->displayPriceAttribute('shipping_amount', false, ' '); ?>
                    <?php endif; ?>
                    <?php $_incl = $block->displayShippingPriceInclTax($_order); ?>

                    <?= /* @escapeNotVerified */ $_excl; ?>
                    <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingBothPrices() && $_incl != $_excl) : ?>
                        (<?= /* @escapeNotVerified */ __('Incl. Tax'); ?> <?= /* @escapeNotVerified */ $_incl; ?>)
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <?php endif; ?>
    </div>
</section>
<?php $_items = $block->getCreditmemo()->getAllItems() ?>

<?php if (count($_items)) : ?>
<div id="creditmemo_items_container">
    <?= $block->getChildHtml('rbsales_creditmemo_items') ?>
</div>
<?php else : ?>
<section class="front__page-section">
    <div class="front__page-section-title">
        <span class="title"><?= /* @escapeNotVerified */ __('Items Refunded') ?></span>
    </div>
    <div class="no-items front__page-section-content"><?= /* @escapeNotVerified */ __('No Items') ?></div>
</section>
<?php endif; ?>

<section class="front__page-section">
    <div class="front__page-section-title">
        <span class="title"><?= /* @escapeNotVerified */ __('Memo Total') ?></span>
    </div>
    <div class="front__page-section-content">
        <div class="front__page-section-item order-comments-history">
            <div class="front__page-section-item-title">
                <span class="title"><?= /* @escapeNotVerified */ __('Credit Memo History') ?></span>
            </div>
            <div class="front__page-section-item-content"><?= $block->getChildHtml('rbsales_order_comments') ?></div>
        </div>
        <div class="front__page-section-item order-totals" id="history_form">
            <div class="front__page-section-item-title">
                <span class="title"><?= /* @escapeNotVerified */ __('Credit Memo Totals') ?></span>
            </div>
            <div class="front__page-section-content"><?= $block->getChildHtml('rbsales_creditmemo_totals') ?></div>
        </div>
    </div>
</section>
