<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $helper \Magento\Search\Helper\Data */
$helper = $this->helper(\Magento\Search\Helper\Data::class);
?>
<div class="block block-search">
    <div class="top-search-btn">
                    <?= /* @escapeNotVerified */ __('Search') ?>
    </div>
    <div class="block block-content">
        <form class="form minisearch" id="search_mini_form" action="<?= /* @escapeNotVerified */ $helper->getResultUrl() ?>" method="get">
            <div class="field search">
                <div class="control">
                    <input id="search"
                           data-mage-init='{"quickSearch":{
                                "formSelector":"#search_mini_form",
                                "url":"<?= /* @escapeNotVerified */ $helper->getSuggestUrl()?>",
                                "destinationSelector":"#search_autocomplete"}
                           }'
                           type="text"
                           name="<?= /* @escapeNotVerified */ $helper->getQueryParamName() ?>"
                           value="<?= /* @escapeNotVerified */ $helper->getEscapedQueryText() ?>"
                           placeholder="<?= /* @escapeNotVerified */ __('What are you looking for ?') ?>"
                           class="input-text"
                           maxlength="<?= /* @escapeNotVerified */ $helper->getMaxQueryLength() ?>"
                           role="combobox"
                           aria-haspopup="false"
                           aria-autocomplete="both"
                           autocomplete="off"/>
                    <div id="search_autocomplete" class="search-autocomplete"></div>
                    <?= $block->getChildHtml() ?>
                </div>
            </div>
            <div class="actions">
                <button type="submit"
                    title="<?= $block->escapeHtml(__('Search')) ?>"
                    class="action search"
                    aria-label="Search"
                >
                    <span><?= /* @escapeNotVerified */ __('Search') ?></span>
                </button>
            </div>
        </form>
    </div>
</div>

<!-- Script for adding active class on click on input box -->
<script>
require([
  "jquery"
  ], function($)
  {
    $('.top-search-btn').click(function() {
        $('.block-search .block-content').toggle("active");
        var searchValue = $('#search').val();
        $('#search').val('').focus().val(searchValue);
    });
    $('.close-search-popup').click(function() {
        $('.block-search .block-content').removeClass("active");
        $('#search').val('');
    });

    $('.minisearch #search').click(function() {
        $('.block-search .block-content').addClass("active");
    });
    $(document).mouseup(function(e)
      {
        var container = $('.block-search .block-content');
        if (!container.is(e.target) && container.has(e.target).length === 0)
        {
          $('.block-search .block-content').removeClass("active");
        }
      });
  });
</script>
<!-- End of script tag -->