<?php
/**
 * KrishTechnolabs
 *
 * PHP version 7
 *
 * @category  KrishTechnolabs
 * @package   Ktpl_ElasticSearch
 * @author    Dhara Bhatti <dhara.bhatti@krishtechnolabs.com>
 * @copyright 2019 (c) KrishTechnolabs (https://www.KrishTechnolabs.com/)
 * @license   https://www.krishtechnolabs.com/LICENSE.txt Krish License
 * @link      https://www.krishtechnolabs.com/
 */
?>

<?php
//@codingStandardsIgnoreFile
/** @var \Ktpl\ElasticSearch\Block\Index\Base $block */

$helper = $this->helper("Ves\Blog\Helper\Data");
?>
<div class="ktpl-search__index ktpl-search__index-ves-blog-post">
    <?= $block->getPager() ?>

        <?php /** @var \Ves\Blog\Model\Post $post */ ?>
        <?php foreach ($block->getCollection() as $post): ?>
            <div class="ves-post post-item">
                <h3 class="post-title">
                    <a href="<?= $post->getUrl() ?>"><?= $post->getTitle() ?></a>
                </h3>

                <div class="post-summary">
                    <?=$helper->subString($post->getShortContent(), 255) ?>
                </div>

                <div class="post-readmore">
                    <a href="<?= $post->getUrl() ?>" title="<?=$post->getTitle() ?>"><?php echo __('Read more') ?></a>
                </div>
            </div>
        <?php endforeach ?>

    <?= $block->getPager() ?>
</div>

