<?php
/**
 * @category   CAT
 * @package    CAT_OfferPage
 * @author     mohd.salman0306@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace CAT\OfferPage\Block;

use Magento\Framework\View\Element\Template\Context;
use CAT\OfferPage\Model\OfferPageFactory;
use Magento\Cms\Model\Template\FilterProvider;
/**
 * OfferPage View block
 */
class OfferPageView extends \Magento\Framework\View\Element\Template
{
    /**
     * @var OfferPage
     */
    protected $_offerpage;
    public function __construct(
        Context $context,
        OfferPageFactory $offerpage,
        FilterProvider $filterProvider
    ) {
        $this->_offerpage = $offerpage;
        $this->_filterProvider = $filterProvider;
        $this->_storeManager = $context->getStoreManager();
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        if($this->getSingleData()){
            $this->pageConfig->getTitle()->set(__($this->getSingleData()->getTitle()));
        }
        return parent::_prepareLayout();
    }

    public function getSingleData()
    {
        $id = $this->getRequest()->getParam('id');
        $offerpage = $this->_offerpage->create();
        $singleData = $offerpage->load($id);
        if($singleData->getOfferPageId() || $singleData['offerpage_id'] && $singleData->getStatus() == 1 && $singleData->getDevice() == 0){
            return $singleData;
        }else{
            return false;
        }
    }

    public function getMediaUrl() {
        return $this->_storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_MEDIA);
    }
}
