<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Sales
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<form id="edit_form" method="post" action="<?= /* @escapeNotVerified */ $block->getSaveUrl() ?>">
    <?= $block->getBlockHtml('formkey')?>
    <?php $_order = $block->getShipment()->getOrder() ?>
    <?php $vId = $block->getShipment()->getVendorId(); ?>
    <?php $vendorOrder = $block->getShipment()->getVendorOrder(); ?>
    <?= $block->getChildHtml('order_info') ?>
    <input type="hidden" name="shipment[vendor_id]" value="<?= $vId ?>"/>
    <input type="hidden" name="shipment[vendor_order_id]" value="<?= $vendorOrder->getVendorOrderId() ?>"/>
    <div class="admin__page-section">
        <div class="admin__page-section-title">
            <span class="title"><?= /* @escapeNotVerified */ __('Payment &amp; Shipping Method') ?></span>
        </div>
        <div class="admin__page-section-content">
            <div class="admin__page-section-item order-payment-method">
                <?php /* Billing Address */ ?>
                <div class="admin__page-section-item-title">
                    <span class="title"><?= /* @escapeNotVerified */ __('Payment Information') ?></span>
                </div>
                <div class="admin__page-section-item-content">
                    <div><?= $block->getPaymentHtml() ?></div>
                    <div class="order-payment-currency"><?= /* @escapeNotVerified */ __('The order was placed using %1.', $_order->getOrderCurrencyCode()) ?></div>
                </div>
            </div>
            <div class="admin__page-section-item order-shipping-address">
                <?php /* Shipping Address */ ?>
                <div class="admin__page-section-item-title">
                    <span class="title"><?= /* @escapeNotVerified */ __('Shipping Information') ?></span>
                </div>
                <div class="admin__page-section-item-content shipping-description-wrapper">
                    <div class="shipping-description-title"><?= $block->escapeHtml($_order->getShippingDescription()) ?></div>
                    <div class="shipping-description-content">
                        <?= /* @escapeNotVerified */ __('Total Shipping Charges'); ?>:

                        <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingPriceIncludingTax()) : ?>
                            <?php $_excl = $block->displayShippingPriceInclTax($vendorOrder); ?>
                        <?php else : ?>
                            <?php $_excl = $block->displayShippingPriceInclTax($vendorOrder); ?>
                        <?php endif; ?>
                        <?php $_incl = $block->displayShippingPriceInclTax($vendorOrder); ?>
                        <?= /* @escapeNotVerified */ $_excl; ?>
                        <?php if ($this->helper('Magento\Tax\Helper\Data')->displayShippingBothPrices() && $_incl != $_excl) : ?>
                        (<?= /* @escapeNotVerified */ __('Incl. Tax'); ?> <?= /* @escapeNotVerified */ $_incl; ?>)
                        <?php endif; ?>
                    </div>
                </div>
                <div><?= $block->getChildHtml('shipment_tracking') ?></div>
            </div>
        </div>
    </div>
    <div id="ship_items_container">
        <?= $block->getItemsHtml() ?>
    </div>
</form>
<script>
require([
    "jquery",
    "mage/mage",
    "prototype"
], function(jQuery){
    jQuery('#edit_form').mage('form').mage('validation');

});
</script>
<?= $block->getChildHtml('shipment_packaging');
