<?php
?>

<!--
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Theme
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
-->
<style>
/*     .search-autocomplete {border-radius: 0 6px 6px 6px;}
.search-autocomplete.three-columns .category-cms-box{width: 268px !important;}
.search-autocomplete.three-columns.two-result .category-cms-box{Width:272px !important;} */
</style>