<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php
/** @var \Amasty\ShopbyBase\Model\FilterSetting $filterSetting */
/** @var \Amasty\Shopby\Model\Layer\Filter\Item $filterItem */
/** @var \Amasty\Shopby\Block\Navigation\FilterRenderer\Category $block */
/** @var \Amasty\Shopby\Model\Layer\Filter\CategoryItems $filterItems */

$filterItems = $block->getFilter()->getItems();
$categoryHelper = $block->getCategoryHelper();
$filterSetting = $block->getFilterSetting();
$filterSubcategoriesView = $block->isFolding();
$filterSubcategoriesType = $filterSubcategoriesView
    ? "amShopbyFilterCategoryLabelsFolding"
    : 'amShopbyFilterCategoryFlyOut';
$filterFoldingClass = $filterSubcategoriesView ? '-folding' : '';
$isParent = $block->isParent($filterItems, $block->getPath());
$filterPathItems = $filterItems->getItems($block->getPath());
$amastyHelper = $this->helper('Ktpl\CategoryView\Helper\AmastyData');
?>
    
<?php if (count($filterPathItems)) : ?>
    <?php foreach ($filterPathItems as $filterItem) : ?>

        <?php $currentPath = ($block->getPath() ?: $filterItems->getStartPath()) . '/' . $filterItem->getValueString(); ?>

         <?php

            $currentUrl =  $block->getRequest()->getUriString();
            $finalCurrentUrl = stripos($currentUrl, "catalogsearch", 0);
            
            if($finalCurrentUrl) { ?>

            <li class="item" data-label="<?= $block->escapeHtml($filterItem->getOptionLabel()) ?>">
                <?php if ($block->isExpandByClick($currentPath)) : ?>
                    <span class="am-collapse-icon"></span>
                <?php endif; ?>

                <?php if ($filterItem->getCount() > 0) : ?>
                    <input
                            name="amshopby[<?= $block->escapeHtml($block->getFilter()->getRequestVar()); ?>][]"
                            value="<?= $block->escapeHtml($filterItem->getValueString()); ?>"
                            type="<?= /* @noEscape */ $block->getInputType(); ?>"
                        <?= /* @noEscape */ $block->checkedFilter($filterItem) ? ' checked' : ''; ?>
                    />

                    

                    <a class="am-filter-item-<?= /* @noEscape */ $block->escapeId(uniqid()) ?>
                        <?= /* @noEscape */ ($isParent) ? 'amshopby-filter-parent' : '' ?>"
                        data-am-js='filter-item-category-<?= /* @noEscape */ $filterSubcategoriesType ?>'
                        href="<?= $block->escapeUrl($filterItem->getUrl()) ?>"
                        <?= /* @noEscape */ $filterItem->getRelNofollow() ? ' rel="nofollow"' : '' ?>
                    >
                <?php endif; ?>

                <?php if ($block->getFilter()->useLabelsOnly()): ?>
                    <span class="label"><?= /* @noEscape */ $filterItem->getOptionLabel() ?></span>
                <?php else : ?>
                    <img src="<?= /* @noEscape */ $categoryHelper->getCategoryImageUrl($filterItem->getValue()) ?>"
                         class="am-category-image"
                         title="<?= $block->escapeHtml($filterItem->getOptionLabel()); ?>"
                         alt="<?= $block->escapeHtml($filterItem->getOptionLabel()); ?>"
                         height="<?= /* @noEscape */ $categoryHelper->getCategoryFilterImageSize(); ?>"
                         width="<?= /* @noEscape */ $categoryHelper->getCategoryFilterImageSize(); ?>"/>
                    <?php if ($block->getFilter()->useLabelsAndImages()) : ?>
                        <span class="label"><?= /* @noEscape */ $filterItem->getOptionLabel() ?></span>
                    <?php endif; ?>
                <?php endif; ?>

                <?php if ($block->getFilterSetting()->isShowProductQuantities()) : ?>
                    <span class="count">
                        <?= /* @noEscape */ $filterItem->getCount() ?>
                        <span class="filter-count-label">
                            <?php $title = ($filterItem->getCount() == 1) ? __('item') : __('items'); ?>
                            <?= $block->escapeHtml($title) ?>
                        </span>
                    </span>
                <?php endif; ?>

                <?php if ($filterItem->getCount() > 0) : ?>
                    </a>
                <?php endif; ?>

                <?php if ($filterItems->getItemsCount($currentPath)) : ?>
                    <?php $level = $block->getLevel();?>
                    <ul class="items items-children level-<?= /* @noEscape */ $level . ' ' . $filterFoldingClass; ?>">
                        <?= /* @noEscape */ $block->renderChildrenItems($currentPath); ?>
                    </ul>
                <?php endif; ?>
            </li>

            <?php } else {

            $category = $amastyHelper->getCurrentCategory();
            $currentCategoryId = $category->getId();

            $filterCategoryId = $filterItem->getValueString();

            if($currentCategoryId == $filterCategoryId) {

            $category = $amastyHelper->getCategory($filterCategoryId);
            $parentId = $category->getParentId();
            
            $parentCategoryData = $amastyHelper->getCategory($parentId);

            $url = $block->getBaseUrl().$parentCategoryData->getUrlPath().".html";

            $allParentCatIds = $category->getParentIds();
            $allChildCatIds = explode(",", $category->getChildren());
        ?>
            <!-- <li>
                <a class="custom-first-level-category" href="<?= $url; ?>">
                        <?php //echo $parentCategoryData->getName(); ?>
                </a>
            </li> -->

            <?php
            $i=0;
            foreach ($allParentCatIds as $parentCategoryData) {
                if ($parentCategoryData) {
                $parentCategorySource = $amastyHelper->getCategory($parentCategoryData);
                $parentUrl = $block->getBaseUrl().$parentCategorySource->getUrlPath().".html"; ?>
                <?php if($parentCategorySource->getName()!="Default Category" && $parentCategorySource->getName()!="Root Catalog") { ?>
                <li class="custom_parent_category_list <?php echo 'level-'.$i++; ?>">
                    <a class="custom-second-level-category" href="<?= $parentUrl; ?>">
                            <?= $parentCategorySource->getName(); ?>
                            <?php 
                                $current_child_category = $amastyHelper->getCategory($parentCategorySource->getId());
                                echo "(".$current_child_category->getProductCollection()->count().")";
                            ?>
                    </a>    
                </li>
            <?php } } } ?>

            <li class="custom_current_category">
                <span class="label">
                    <?= /* @noEscape */ $filterItem->getOptionLabel() ?>
                    <?php 
                        $current_child_category = $amastyHelper->getCategory($filterItem->getValueString());
                        echo "(".$current_child_category->getProductCollection()->count().")";
                    ?>
                </span>
            </li>

            <?php 
            foreach ($allChildCatIds as $childCategoryData) {
                if ($childCategoryData) {
                $categorySource = $amastyHelper->getCategory($childCategoryData);
                $childurl = $block->getBaseUrl().$categorySource->getUrlPath().".html"; ?>
                <li class="custom_child_category_list">
                    <a href="<?= $childurl; ?>">
                            <?= $categorySource->getName(); ?>
                            <?php 
                                $current_child_category = $amastyHelper->getCategory($categorySource->getId());
                                echo "(".$current_child_category->getProductCollection()->count().")";
                            ?>
                    </a>    
                </li>
            <?php } } ?>

        <?php } }  ?>

    <?php endforeach; ?>

    <script type="text/x-magento-init">
        {
            "[data-am-js='filter-item-category-<?= /* @noEscape */ $filterSubcategoriesType ?>']": {
                "<?= /* @noEscape */ $filterSubcategoriesType ?>" : {
                    "collectFilters": <?= /* @noEscape */ $block->collectFilters(); ?>
                }
            }
        }
    </script>
    <script type="text/javascript">
	require(["jquery"], function($) {
	    if($("body").hasClass("catalogsearch-result-index")) {
	        $("ul.am-filter-items-attr_category_ids").parentsUntil(".filter-options").hide();
	    }
	});
    </script>
<?php endif; ?>
