<?php
/**
 * @var $block \RB\Catalog\Block\Product\View\ProductVendor
 */
?>
<?php if ($vendorProduct = $block->getProductDefaultVendor()) { ?>
<div class="prod-warrant-description" id="product_warrant_description">
    <?php if ($vendorProduct->getWarrantyDescription()) { ?>
<label><?= __('Warranty'); ?> : </label>
        <?= $vendorProduct->getWarrantyDescription(); ?>
<?php } ?>
</div>
<?php } ?>
   

<style>
       .catalog-product-view .prod-warrant-description{
display: none;
}
</style>