<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Sales\Block\Order\History $block */

?>
<?php $_orders = $block->getOrders(); ?>
<?= $block->getChildHtml('info') ?>
<?php
$post = $this->getRequest()->getParams();
if(isset($post)){
$msg =/* @escapeNotVerified */ __('No Result Found. <a href="'.$this->getUrl('sales/order/history').'">Reset My Orders</a>');
}else{
    $msg=/* @escapeNotVerified */ __('You have placed no orders.');
}
?>

<?= $block->getChildHtml('info') ?>
<?php if ($_orders && count($_orders)): ?>
    <div class="table-wrapper orders-history co-search">
        <table class="data table table-order-items history" id="my-orders-table">
            <caption class="table-caption"><?= /* @escapeNotVerified */ __('Orders') ?></caption>
            <thead>
                <tr>
                    <form method='get' >
                    <td scope="col" class="col date" id="calendar_inputField" colspan="5">
                        <div class="form-date">
                            <input type="text" placeholder="Purchase Date From" id="date-from" name="from_date" value="<?= $this->getRequest()->getParam('from_date')?>"/>
                        </div>
                        <div class="to-date">
                            <input type="text" id="date-to" name="to_date" placeholder="Purchase Date To" value="<?= $this->getRequest()->getParam('to_date')?>"/>
                        </div>
                        <div class="date-filter actions">
                            <button type="submit" value="Filter"><?=__('Apply Filter')?></button>
                            <a href="<?= $this->getUrl('sales/order/history') ?>"><button type="reset" value="Filter"><?=__('Reset Filter')?></button></a>
                        </div>
                    </td>
                    <!-- <th scope="col" class="col actions" colspan="2">
                        <button type="submit" value="Filter"><?=__('Apply Filter')?></button>
                        <a href="<?= $this->getUrl('sales/order/history') ?>"><button type="reset" value="Filter"><?=__('Reset Filter')?></button></a>
                    </th> -->

                    </form>
                    <!-- <th scope="col" class="col actions"></th>
                    <th scope="col" class="col actions"></th><th scope="col" class="col actions"></th> -->
                </tr>
                <tr>
                    <th scope="col" class="col id"><?= /* @escapeNotVerified */ __('Order #') ?></th>
                    <th scope="col" class="col date"><?= /* @escapeNotVerified */ __('Date') ?></th>
                    <?= /* @noEscape */ $block->getChildHtml('extra.column.header') ?>
                    <th scope="col" class="col shipping"><?= /* @escapeNotVerified */ __('Ship To') ?></th>
                    <th scope="col" class="col total"><?= /* @escapeNotVerified */ __('Order Total') ?></th>
                    <?php if($block->isMagentoOrderStatusDisplayed()) { ?>
                    <th scope="col" class="col status"><?= /* @escapeNotVerified */ __('Status') ?></th>
                    <?php } ?>
                    <th scope="col" class="col actions"><?= /* @escapeNotVerified */ __('Action') ?></th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($_orders as $_order): ?>
                    <tr>
                        <td data-th="<?= $block->escapeHtml(__('Order #')) ?>" class="col id"><?= /* @escapeNotVerified */ $_order->getRealOrderId() ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Date')) ?>" class="col date"><?= /* @escapeNotVerified */ $block->formatDate($_order->getCreatedAt()) ?></td>
                        <?php $extra = $block->getChildBlock('extra.container'); ?>
                        <?php if ($extra): ?>
                            <?php $extra->setOrder($_order); ?>
                            <?= /* @noEscape */ $extra->getChildHtml() ?>
                        <?php endif; ?>
                        <td data-th="<?= $block->escapeHtml(__('Ship To')) ?>" class="col shipping"><?= $_order->getShippingAddress() ? $block->escapeHtml($_order->getShippingAddress()->getName()) : '&nbsp;' ?></td>
                        <td data-th="<?= $block->escapeHtml(__('Order Total')) ?>" class="col total"><?= /* @escapeNotVerified */ $_order->formatPrice($_order->getGrandTotal()) ?></td>
                        <?php if($block->isMagentoOrderStatusDisplayed()) { ?>
                            <td data-th="<?= $block->escapeHtml(__('Status')) ?>" class="col status"><?= /* @escapeNotVerified */ $_order->getStatusLabel() ?></td>
                        <?php } ?>
                        <td data-th="<?= $block->escapeHtml(__('Actions')) ?>" class="col actions">
                            <a href="<?= /* @escapeNotVerified */ $block->getViewUrl($_order) ?>" class="action view">
                                <span><?= /* @escapeNotVerified */ __('View Order') ?></span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
    <?php if ($block->getPagerHtml()): ?>
        <div class="order-products-toolbar toolbar bottom"><?= $block->getPagerHtml() ?></div>
    <?php endif ?>
<?php else: ?>
     <div class="message info empty"><span><?= $msg ?></span></div>
<?php endif ?>
<script>
        require([
            "jquery",
            "mage/calendar"
        ], function ($) {
             $("#calendar_inputField").dateRange({
                buttonText: 'Select Date',
        from: {
            id: 'date-from'
        },
        to: {
            id: 'date-to'
        }
            });
        });
</script>
