<?php
/** @var \Ktpl\CityDropdown\Block\Checkout\Cities $block */
?>

<div class="pp-buttons-container">

    <?php
    $cities = $block->citiesJson();

    ?>
</div>
<script>
    require(
        [
            'jquery'
        ],
        function($) {
         $eaCitiesJson = <?php echo $cities?>;

        });
</script>
<?php //echo $cities; ?>
<script type="text/x-magento-init">
    {
        "#form-validate": {
            "addressValidation": {}
        }
    }
</script>

