<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php
/** @var \Magento\Catalog\Pricing\Render\FinalPriceBox $block */

/** ex: \Magento\Catalog\Pricing\Price\RegularPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** ex: \Magento\Catalog\Pricing\Price\FinalPrice */
/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
$productId = $block->getSaleableItem()->getId();
$viphelper = $this->helper('CAT\VIP\Helper\Data');
$defaultVid = $block->getSaleableItem()->getVendorId();
$productVid = $block->getSaleableItem()->getVendorId();
$pricehelper = $this->helper('Magento\Framework\Pricing\Helper\Data');
$catalogHelper = $this->helper('CAT\VIP\Helper\UpdatesData');
if($productVid == ''){
    $defaultVendorProduct = $catalogHelper->getProductDefaultVendor($productId);
    if($defaultVendorProduct){
        $productVid = $defaultVendorProduct->getVendorId();
   }
}

/*if(empty($productVid)){

   //redirect if product Out od stock
     $_responseFactory  = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Framework\App\ResponseInterface::class);
     $storeManager  = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Store\Model\StoreManagerInterface::class);
     $_responseFactory->setRedirect($storeManager->getStore()->getBaseUrl(), 301)->sendResponse();
}*/

$isvip = $viphelper->isvipProduct($productId,$productVid);
?>
<?php if ($block->hasSpecialPrice()): ?>
    <?php if($isvip){
        
         $aplyedvipPrice = $viphelper->applyvipProductDiscountPrice($productId,$finalPriceModel->getAmount()->getValue(),$productVid) ;
     ?>
        <span class="price-container price-final_price tax weee" style="display: block;">
        <span class="price-wrapper "><span class="price"><?= $pricehelper->currency($aplyedvipPrice, true, false)?></span></span>
        <meta itemprop="price" content="<?=$aplyedvipPrice;?>">
        <meta itemprop="priceCurrency" content="IQD">
    </span>
    <?php } else { ?>
    <div class="normal-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label'     => __('Special Price'),
            'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
            'price_type'        => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ]); ?>
    </div>
    <?php } ?> 
    <div class="old-price sly-old-price">
        <?php /* @escapeNotVerified */ echo $block->renderAmount($priceModel->getAmount(), [
            'display_label'     => __('Regular Price'),
            'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
            'price_type'        => 'oldPrice',
            'include_container' => true,
            'skip_adjustments'  => true
        ]); ?>
    </div>
    <?php $percentageOff =  round(($priceModel->getAmount()->getValue() - $finalPriceModel->getAmount()->getValue()) * 100 / $priceModel->getAmount()->getValue());?>
    <span class="discount-box saving_percent sly-old-price"><?php echo $percentageOff;  echo __("% off")?></span>
    <?php /*
        $currencysymbol = \Magento\Framework\App\ObjectManager::getInstance()->get(\Magento\Store\Model\StoreManagerInterface::class);
        $currency = $currencysymbol->getStore()->getCurrentCurrencyCode();
        $savingPrice = $priceModel->getAmount()->getValue() - $finalPriceModel->getAmount()->getValue();
    */?>
    <span class="saving_price sly-old-price">
        <!--<span><?php /*echo __('Saving'); */?></span> <span><?php /*echo __($currency); */?></span><span><?php /* echo $savingPrice; */?></span>-->
    </span>
    <br>
    <?php if($isvip){

            $ProductPrice = $finalPriceModel->getAmount()->getValue();
            // Fixed discount
            if($isvip->getDiscountType() == 'Fixed'){
                $vipPrice = ($ProductPrice - (float)$isvip->getDiscount());
            }
            else{
                $discount = (float)$isvip->getDiscount();
                $discountPrice = (($ProductPrice / 100) * $discount);
                $vipPrice = ($ProductPrice - $discountPrice);
            }
            if($aplyedvipPrice == $vipPrice){
                $vipalredyapplyed = true;
            }
            else{
                $vipalredyapplyed = false;
            }
            $percentageOff =  round(($finalPriceModel->getAmount()->getValue() - $vipPrice) * 100 / $finalPriceModel->getAmount()->getValue());

            if($vipalredyapplyed){
               $vipPrice = $ProductPrice;
            }
            //$finalPriceModel->getAmount()->setValue($vipPrice)
            
            //$finalPriceModel->getAmount()->setValue($vipPrice)
        ?>
        <div class="old-price sly-old-price">
            <span class="price-container price-final_price tax weee">
                <span id="vip-price-413251" data-price-amount="$vipPrice" data-price-type="vipPrice" class="price-wrapper "><span style="font-size: 18px;" class="<?=($vipalredyapplyed)? 'price':''?>"><?= $pricehelper->currency($vipPrice, true, false)?></span></span>
            </span>
             <span style="font-size: 12px;font-family: 'Proxima Nova', 'Helvetica Neue', Arial, sans-serif;color: red;"><?php echo $percentageOff;  echo __("% off VIP");?></span>
            <?php if($defaultVid){ ?>
            <br>
            <span style="font-size: 12px;font-family: 'Proxima Nova', 'Helvetica Neue', Arial, sans-serif;color: red;"> <?php echo __("Limit %1 Per Customer",$isvip->getIndQty());?></span>
            <?php } ?>
        </div>


    <?php }
    ?>
    <div class="old-price sly-old-price" id="vipprice" style="display: none;">
            <span class="price-container price-final_price tax weee">
                <span id="vip-price-product" class="price-wrapper"><span style="font-size: 18px;" class=""></span></span>
            </span>
    </div>
    <span class="vippercent" style="display: none;font-size: 12px;font-family: 'Proxima Nova', 'Helvetica Neue', Arial, sans-serif;color: red;"><span></span><?php  echo __("% off VIP");?></span>

     
<?php else: ?>
     <?php if($isvip){
        
         $aplyedvipPrice = $viphelper->applyvipProductDiscountPrice($productId,$finalPriceModel->getAmount()->getValue(),$productVid) ;
     ?>
        <span class="price-container price-final_price tax weee" style="display: block;">
        <span class="price-wrapper "><span class="price"><?= $pricehelper->currency($aplyedvipPrice, true, false)?></span></span>
        <meta itemprop="price" content="<?=$aplyedvipPrice;?>">
        <meta itemprop="priceCurrency" content="IQD">
    </span>
    <?php } else { ?>
    <?php /* @escapeNotVerified */ echo $block->renderAmount($finalPriceModel->getAmount(), [
        'price_id'          => $block->getPriceId('product-price-' . $idSuffix),
        'price_type'        => 'finalPrice',
        'include_container' => true,
        'schema' => $schema
    ]); } ?>
    <?php if($isvip){
             $ProductPrice = $finalPriceModel->getAmount()->getValue();
            // Fixed discount
            if($isvip->getDiscountType() == 'Fixed'){
                $vipPrice = ($ProductPrice - (float)$isvip->getDiscount());
            }
            else{
                $discount = (float)$isvip->getDiscount();
                $discountPrice = (($ProductPrice / 100) * $discount);
                $vipPrice = ($ProductPrice - $discountPrice);
            }
            if($aplyedvipPrice == $vipPrice){
                $vipalredyapplyed = true;
            }
            else{
                $vipalredyapplyed = false;
            }
            $percentageOff =  round(($finalPriceModel->getAmount()->getValue() - $vipPrice) * 100 / $finalPriceModel->getAmount()->getValue());
            if($vipalredyapplyed){
               $vipPrice = $ProductPrice;
            }
            //$finalPriceModel->getAmount()->setValue($vipPrice)
        ?>
        <div class="old-price sly-old-price">
            <span class="price-container price-final_price tax weee">
                <span id="vip-price-413251" data-price-amount="$vipPrice" data-price-type="vipPrice" class="price-wrapper "><span style="font-size: 18px;" class="<?=($vipalredyapplyed)? 'price':''?>"><?= $pricehelper->currency($vipPrice, true, false)?></span></span>
            </span>
            <span style="font-size: 12px;font-family: 'Proxima Nova', 'Helvetica Neue', Arial, sans-serif;color: red;"><?php echo $percentageOff;  echo __("% off VIP");?></span>
            <?php if($defaultVid){ ?>
            <br>
            <span style="font-size: 12px;font-family: 'Proxima Nova', 'Helvetica Neue', Arial, sans-serif;color: red;"> <?php echo __("Limit %1 Per Customer",$isvip->getIndQty());?></span>
            <?php } ?>
        </div>

    <?php }
    ?>
    <div class="old-price sly-old-price" id="vipprice" style="display: none;">
            <span class="price-container price-final_price tax weee">
                <span id="vip-price-product" class="price-wrapper"><span style="font-size: 18px;" class=""></span></span>
            </span>
        </div>
        <span class="vippercent" style="display: none;font-size: 12px;font-family: 'Proxima Nova', 'Helvetica Neue', Arial, sans-serif;color: red;"><span></span><?php  echo __("% off VIP");?></span>
<?php endif; ?>


<?php if ($block->showMinimalPrice()): ?>
    <?php if ($block->getUseLinkForAsLowAs()):?>
        <a href="<?= /* @escapeNotVerified */ $block->getSaleableItem()->getProductUrl() ?>" class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
        </a>
    <?php else:?>
        <span class="minimal-price-link">
            <?= /* @escapeNotVerified */ $block->renderAmountMinimal() ?>
        </span>
    <?php endif?>
<?php endif; ?>


