<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Theme
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */

?>
<?php
/**
 * @var $block \Magedelight\Theme\Block\Sellerhtml\Widget\Button
 */
?>
<?= /* @noEscape */ $block->getBeforeHtml(); ?>
<button <?= /* @noEscape */ $block->getAttributesHtml(), $block->getUiId(); ?>>
    <span><?= /* @noEscape */ $block->getLabel(); ?></span>
</button>
<?= /* @noEscape */ $block->getAfterHtml(); ?>
