<?php
/**
 * KrishTechnolabs
 *
 * PHP version 7
 *
 * @category  KrishTechnolabs
 * @package   Ktpl_ElasticSearch
 * @author    Dhara Bhatti <dhara.bhatti@krishtechnolabs.com>
 * @copyright 2019 (c) KrishTechnolabs (https://www.KrishTechnolabs.com/)
 * @license   https://www.krishtechnolabs.com/LICENSE.txt Krish License
 * @link      https://www.krishtechnolabs.com/
 */
?>

<?php
//@codingStandardsIgnoreFile
/** @var \Ktpl\ElasticSearch\Block\Index\Base $block */
?>
<div class="ktpl-search__index ktpl-search__index-ves-blog-post">
    <?= $block->getPager() ?>

    <?php /** @var \Mageplaza\Blog\Model\Post $post */ ?>
    <?php foreach ($block->getCollection() as $post): ?>
        <div class="mageplaza-post post-item">
            <h3 class="post-title">
                <a href="<?= $post->getUrl() ?>"><?= $post->getName() ?></a>
            </h3>

            <div class="post-summary">
                <?= $post->getShortDescription() ?>
            </div>
        </div>
    <?php endforeach ?>

    <?= $block->getPager() ?>
</div>

