<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Backend
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */le

?>
<?php
/* @var $block \Magedelight\Backend\Block\Widget\Form\Renderer\Fieldset\Element */
$element = $block->getElement();
$note = $element->getNote() ? '<div class="note rb-frontend__field-note" id="' . $element->getId() . '-note">' . $element->getNote() . '</div>' : '';
$elementBeforeLabel = $element->getExtType() == 'checkbox rb-frontend__control-checkbox' || $element->getExtType() == 'radio rb-frontend__control-radio';
$addOn = ($element->getBeforeElementHtml() || $element->getAfterElementHtml()) && !$element->getNoWrapAsAddon();
$fieldId = ($element->getHtmlContainerId()) ? ' id="' . $element->getHtmlContainerId() . '"' : '';
$fieldClass = "rb-frontend__field field field-{$element->getId()} {$element->getCssClass()}";
$fieldClass .= ($elementBeforeLabel) ? ' choice' : '';
$fieldClass .= ($addOn) ? ' with-addon' : '';
$fieldClass .= ($element->getRequired()) ? ' required _required' : '';
$fieldClass .= ($note) ? ' with-note' : '';
$fieldClass .= (!$element->getLabelHtml()) ? ' no-label' : '';

$fieldAttributes = $fieldId . ' class="' . $fieldClass . '" '
    . $block->getUiId('form-field', $element->getId())
    . ($element->getFieldExtraAttributes() ? ' ' . $element->getFieldExtraAttributes() : '');
?>

<?php if (!$element->getNoDisplay()) : ?>
    <?php if ($element->getType() == 'hidden') : ?>
        <?= $element->getElementHtml() ?>
    <?php else : ?>
    <div<?= /* @escapeNotVerified */ $fieldAttributes ?>>
        <?php if ($elementBeforeLabel) : ?>
            <?= $element->getElementHtml() ?>
            <?= $element->getLabelHtml('', $element->getScopeLabel()) ?>
            <?= /* @escapeNotVerified */ $note ?>
        <?php else : ?>
            <?= $element->getLabelHtml('', $element->getScopeLabel()) ?>
            <div class="rb-frontend__field-control control">
                <?= /* @escapeNotVerified */ ($addOn) ? '<div class="rb-frontend__field">' . $element->getElementHtml() . '</div>' : $element->getElementHtml(); ?>
                <?= /* @escapeNotVerified */ $note ?>
            </div>
        <?php endif; ?>
    </div>
    <?php endif; ?>
<?php endif; ?>
