<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Newsletter\Block\Subscribe $block */

?>
<div class="block newsletter">


<?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('footer-contact-address-box')->toHtml();?>

    <div class="title"><h3><?= $block->escapeHtml(__('Newsletter')) ?></h3></div>
    <div class="content">
        <form class="form subscribe"
            novalidate
            action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
            method="post"
            data-mage-init='{"validation": {"errorClass": "mage-error"}}'
            id="newsletter-validate-detail">
            <div class="field newsletter">
                <div class="control">
                    <label for="newsletter">
                        <span class="label">
                            <?= $block->escapeHtml(__('Sign Up for Our Newsletter:')) ?>
                        </span>
                        <input name="email" type="email" id="newsletter"
                               placeholder="<?= $block->escapeHtml(__('Your email address')) ?>"
                               data-mage-init='{"mage/trim-input":{}}'
                               data-validate="{required:true, 'validate-email':true}"
                        />
                    </label>
                </div>
            </div>
            <div class="actions">
                <button class="action subscribe primary"
                        title="<?= $block->escapeHtmlAttr(__('Subscribe')) ?>"
                        type="submit"
                        aria-label="Subscribe">
                    <span><?= $block->escapeHtml(__('Subscribe')) ?></span>
                </button>
            </div>
        </form>
    </div>
</div>

<!-- All categories custom menu second level ul inline style remove to visible -->
<script type="text/javascript">
    require(['jquery'], function ($) {
        $( document ).ready(function() {
             setInterval(function(){ 
                if($("ul").hasClass("all-cats-ul-items2")){
                    $(".all-cats-ul-items2").attr("style","");
             }
          }, 1000);           
        });
});
</script>
