<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_VendorPromotion
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<?php
$_rule = $this->getRule();
?>

<div class="page-title">
    <h1 class="vendor-cart-title">
        <?php echo $_rule->getId() ? __('Edit Cart Price Rule "%1"', $_rule->getData('name')) : __('Create New Cart price Rule') ?>
    </h1>
    <span class="required"><?php echo __('* Indicated Required Fields') ?></span>
</div>
<?php echo $this->getLayout()->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('rbvendor/salesrule/save', ['_current' => true]) ?>" method="post" id="rule-edit-form">
    <input type="hidden" name="id" value="<?php echo $_rule->getId() ?>" />
    <?php
    foreach ($this->getForm()->getElements() as $element) {
        echo $element->toHtml();
    }
    ?> 

    <div class="buttons-set">
        <span class="rule-edit-form-loader" style="display:none" id="rule-edit-form-loader"><?php echo __('Please wait, submitting...') ?></span>
        <button class="form-button action button primary btn-submit" type="button" onclick="rbpromoEditFormSubmit(this, false)" name="send"><span><?php echo __('Save') ?></span></button>
        <div class="clearer"></div><br/>
        <p><a href="<?php echo $this->getUrl('rbvendor/salesrule') ?>">&laquo; <?php echo __('Return to rules list') ?></a></p>
    </div>
</form>

<script type="text/javascript">
    require(["jquery", "mage/mage", "mage/calendar"], function ($) {
        if($("#coupon_type").val() == '1') {
            $('.coupon_code').css('display', 'none');
        }
        $("#coupon_type").on('change', function (e) {
            $('.coupon_code').css('display', 'block');
            if ($(this).val() == '1') {
                $('#coupon_code').val("");
                $('.coupon_code').css('display', 'none');
            }else{
                $('#coupon_code').val();
            }
        });

        $("#rule-edit-form").dateRange({
            buttonText: "",
            showOn: "button",
            dateFormat: "<?php echo $block->getLocaleDate()->getDateFormatWithLongYear() ?>",
            from: {
                id: "from_date"
            },
            to: {
                id: "to_date"
            }
        });
        var rbpromoEditForm = $('#rule-edit-form');
        rbpromoEditForm.mage('validation', {});
        window.rbpromoEditFormSubmit = function (elem) {
            $(elem).hide();
            $('#rule-edit-form-loader').show();
            var res = false;
            if (rbpromoEditForm.valid()) {
                res = true;
                rbpromoEditForm.submit();
            } else {
                $(elem).show();
                $('#rule-edit-form-loader').hide();
            }
            return res;
        }

    });
</script>

<script type="text/javascript">
    require(["jquery", "prototype", "domReady!"], function (jQuery) {
        var couponTypeSpecific = '<?php echo \Magento\SalesRule\Model\Rule::COUPON_TYPE_SPECIFIC ?>';

        function disableEnableCouponsTabContent(disable) {
            var containerId = 'coupons_fieldset';
            if ($(containerId)) {
                var dataFields = $(containerId).select('input', 'select', 'textarea', 'button');
                for (var i = 0; i < dataFields.length; i++) {
                    disable ? dataFields[i].disable().addClassName('disabled')
                            : dataFields[i].enable().removeClassName('disabled');
                }
            }
            disable ? $('rule_coupon_code').enable() : $('rule_coupon_code').disable();
        }

        function handleCouponsTabContentActivity() {
            disableEnableCouponsTabContent(!$('rule_use_auto_generation').checked);
        }

        function handleCouponTypeChange() {
            $('rule_coupon_type').observe('change', function () {
                var disable = $('rule_coupon_type').value != couponTypeSpecific;
                if (!disable) {
                    disable = !$('rule_use_auto_generation').checked;
                }
                disableEnableCouponsTabContent(disable);
            });
        }

        function refreshCouponCodesGrid(grid, gridMassAction, transport) {
            grid.reload();
            gridMassAction.unselectAll();
        }

        function generateCouponCodes(idPrefix, generateUrl, grid) {
            $(idPrefix + 'information_fieldset').removeClassName('ignore-validate');
            var validationResult = $(idPrefix + 'information_fieldset').select('input',
                    'select', 'textarea').collect(function (elm) {
                return Validation.validate(elm, {
                    useTitle: false,
                    onElementValidate: function () {
                    }
                });
            }).all();

            $(idPrefix + 'information_fieldset').addClassName('ignore-validate');

            if (!validationResult) {
                return;
            }
            var elements = $(idPrefix + 'information_fieldset').select('input', 'select', 'textarea');

            elements = elements.concat(
                    $$('#rule_uses_per_coupon'),
                    $$('#rule_uses_per_customer'),
                    $$('#rule_to_date')
                    );

            var params = Form.serializeElements(elements, true);
            params.form_key = FORM_KEY;
            $('messages').update();
            var couponCodesGrid = eval(grid);
            new Ajax.Request(generateUrl, {
                parameters: params,
                method: 'post',
                onComplete: function (transport, params) {
                    var response = false;
                    if (transport && transport.responseText) {
                        response = eval('(' + transport.responseText + ')');
                    }
                    if (couponCodesGrid) {
                        couponCodesGrid.reload();
                    }
                    if (response && response.messages) {
                        $('messages').update(response.messages);
                    }
                    if (response && response.error) {
                        alert(response.error);
                    }
                }
            });
        }

        Ajax.Responders.register({
            onComplete: function () {
                if ($('coupons_fieldset')
                        && $('coupons_fieldset').visible()
                        && Ajax.activeRequestCount == 0
                        ) {
                    handleCouponsTabContentActivity();
                }
            }
        });
    });
</script>
<script type="text/javascript">
require([
    'jquery',
    'jquery/ui',
    'jquery/validate',
    'mage/mage',
    'mage/translate'
], function ($) {
    $(document).ready(function () {
        $(".field-tooltip").on('click', function (event) {
            if($(this).hasClass('_active'))
            {
                $(this).removeClass('_active');
                $(this).find('.field-tooltip-content').removeClass('_active');
            } else {
                $(".field-tooltip").removeClass('_active');
                $(".field-tooltip-content").removeClass('_active');
                $(this).addClass('_active');
                $(this).find('.field-tooltip-content').addClass('_active');
            }
        });
    });
});
</script>
