<div class="scan_product_container">
<?php
$deliverytype = $block->getRequest()->getParam('deliverytype');
$returntype = $block->getRequest()->getParam('returntype');
$scanLimit = $block->getScanLimit();
?>
<input type="hidden" value="0" name="recordcount" />
<form id="vendor-to-warehouse" method="post">
   <table class="data-grid data-grid-draggable">
    <thead>
        <tr>
			<th class="data-grid-th"><?= __("ID"); ?></th>
            <th class="data-grid-th"><?= __("Main Order ID"); ?></th>
            <th class="data-grid-th"><?= __("Sub Order ID"); ?></th>
            <th class="data-grid-th"><?= __("Product Name"); ?></th>
            <th class="data-grid-th"><?= __("Price"); ?></th>
            <th class="data-grid-th"><?= __("Qty"); ?></th>
            <th class="data-grid-th"><?= __("Main Order Status"); ?></th>
            <th class="data-grid-th"><?= __("Sub Order Status"); ?></th>
        </tr>
    </thead>
    <tbody id="rowcontainer">
        <tr class="data-grid-tr-no-data noDataraw">
            <td colspan="8"><?= __("We couldn't find any records."); ?></td>
        </tr>
    </tbody>
   </table>
   <button type="button" name="Submit" class="primary initSaveData" onclick="sendEventData()" style="margin-top: 10px;"><?= __("Submit"); ?></button>
</form>
</div>


<script type="text/javascript">
    require([
        'jquery',
        'mage/url',
        'Magento_Ui/js/modal/alert'
    ], function ($, url, dialog) {

        /*..Initialize global array for scanned barcodenumber and basic settings..*/
        var listBarcode = [];
        $('.initSaveData').hide();
        $('.noDataraw').show();

        $("input[name=barcode]").live('keydown',function(e) {
            if (e.which == 13) {
                e.stopImmediatePropagation();
                var barcodescan =$('input[name=barcode]').attr('value');
                var recordcount =$('input[name=recordcount]').attr('value');
                var scannedbarcode = $.trim(barcodescan);
                /*var substr = scannedbarcode.split(/\s+/);
                var current = null;
                for (i = 0; i < substr.length; ++i) {
                    if (substr[i] != current) {
                        current = substr[i];
                    } else {
                        dialog({
                            title: $.mage.__('Notice!!!'),
                            content: $.mage.__('You scanned duplicate barcode number, please scan new barcode.')
                        });
                        $('input[name=barcode]').val("");
                        $( "input[name=barcode]" ).focus();
                        return false;
                    }
                }*/
                /*..Check for limited/duplicate barcode scan ..*/
                if(scannedbarcode == "") {
                    return false;
                } else if($.inArray(scannedbarcode, listBarcode) !== -1) {
                    dialog({
                        title: $.mage.__('Notice!!!'),
                        content: $.mage.__('You scanned duplicate barcode number, please scan new barcode.')
                    });
                    $('input[name=barcode]').val("");
                    $( "input[name=barcode]" ).focus();
                    return false;
                } else if(listBarcode.length > <?= $scanLimit - 1 ?>) {
                    dialog({
                    title: $.mage.__('Notice!!!'),
                    content: $.mage.__('You have to Submit first <?= $scanLimit; ?> line items.')
                });
                    $('input[name=barcode]').val("");
                    $( "input[name=barcode]" ).focus();
                    return false;
                } else {
                    listBarcode.push(scannedbarcode);
                }

                /*..Scan Barcode blur event ajax call..*/
                if(scannedbarcode != "") {
                var action = "<?= $block->getUrl('ktpl_warehousemanagement/warehousemanagement/fetchproduct', ['form_key' => $block->getFormKey()])?>";
                  var codevalue = {'scannedbarcode' : scannedbarcode };
                  $.ajax({
                        url: action,
                        showLoader: true,
                        type: 'POST',
                        data: {
                            scannedbarcode: scannedbarcode,
                            eventype: <?= $deliverytype; ?>,
                            returntype: <?= $returntype; ?>,
                            recordcount: recordcount
                        },
                        complete: function(response) {
                            $('.noDataraw').hide();
                            $('#rowcontainer').append(response.responseJSON.output);
                            $('.loading-mask').hide();
                            $('input[name=barcode]').val("");
                            $('input[name=recordcount]').val(parseInt(recordcount)+1);
                            $( "input[name=barcode]").focus();
                            $('.initSaveData').show();
                        },
                    error: function(response) {
							var recordcount =$('input[name=recordcount]').attr('value');
                            $('.loading-mask').hide();
                            listBarcode.pop(scannedbarcode);
                            dialog({
                                title: $.mage.__('Notice!!!'),
                                content: $.mage.__('Scanned Record not found!'),
                                actions: {
                                    always: function(){
                                        $('input[name=barcode]').val("");
                                        $( "input[name=barcode]").focus();
                                    }
                                }
                            });
                        }
                    });
                } else {
                    return false;
                }
            }
        });

        /*..Submit Line item data..*/
        this.sendEventData = function() {
            var customurl = "<?= $block->getUrl('ktpl_warehousemanagement/warehousemanagement/saveevent', ['form_key' => $block->getFormKey()])?>";
            $.ajax({
                url : customurl,
                type : 'POST',
                showLoader: true,
                data: {
                        eventype: <?= $deliverytype; ?>
                    },
                data : $('#vendor-to-warehouse').serialize(),
                success: function(msg) {
                    if(msg['duplicateInDb'] == 0) {
                        dialog({
                            title: $.mage.__('Error!!!'),
                            content: $.mage.__('Your scanned line item already saved.'),
                            actions: {
                                always: function(){
                                    window.location.reload();
                                }
                            }
                        });
                    } else {
                        dialog({
                            title: $.mage.__('Success!!!'),
                            content: $.mage.__('Your record has been saved successfully.'),
                            actions: {
                                always: function(){
                                    window.location.reload();
                                }
                            }
                        });
                    }
                }
            });
        }
        return this;
    });
</script>