<?php
/**
 * @category   CAT
 * @package    CAT_OfferPage
 * @author     mohd.salman0306@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace CAT\OfferPage\Controller\Adminhtml\Items;

class Save extends \CAT\OfferPage\Controller\Adminhtml\Items
{
    /**
     * @return \Magento\Framework\App\ResponseInterface|\Magento\Framework\Controller\ResultInterface|void
     */
    public function execute()
    {
        if ($this->getRequest()->getPostValue()) {
            try {
                $model = $this->_objectManager->create('CAT\OfferPage\Model\OfferPage');
                $data = $this->getRequest()->getPostValue();
                $dynamicRows = $this->getRequest()->getParam('dynamic_rows');
                $data['additional_info'] = '';
                $data['default_image'] = '';
                if($dynamicRows && count($dynamicRows) > 0) {
                    $data['additional_info'] = json_encode($dynamicRows);
                    $data['default_image'] = (!empty($dynamicRows[0]['image']) && (count($dynamicRows[0]['image']) > 0)) ? $dynamicRows[0]['image'][0]['file']: '';
                }
                unset($data['dynamic_rows']);

                $inputFilter = new \Zend_Filter_Input(
                    [],
                    [],
                    $data
                );
                $data = $inputFilter->getUnescaped();
                $id = $this->getRequest()->getParam('id');
                if ($id) {
                    $model->load($id);
                    if ($id != $model->getId()) {
                        throw new \Magento\Framework\Exception\LocalizedException(__('The wrong item is specified.'));
                    }
                }

                if (empty($data['offerpage_id'])) {
                    unset($data['offerpage_id']);
                }
                $model->setData($data);
                $session = $this->_objectManager->get('Magento\Backend\Model\Session');
                $session->setPageData($model->getData());
                $model->save();
                $this->messageManager->addSuccess(__('You saved the item.'));
                $session->setPageData(false);
                if ($this->getRequest()->getParam('back')) {
                    $this->_redirect('cat_offerpage/*/edit', ['id' => $model->getId()]);
                    return;
                }
                $this->_redirect('cat_offerpage/*/');
                return;
            } catch (\Magento\Framework\Exception\LocalizedException $e) {
                $this->messageManager->addErrorMessage($e->getMessage());
                $id = (int)$this->getRequest()->getParam('iofferpage_idd');
                if (!empty($id)) {
                    $this->_redirect('cat_offerpage/*/edit', ['id' => $id]);
                } else {
                    $this->_redirect('cat_offerpage/*/new');
                }
                return;
            } catch (\Exception $e) {
                $this->messageManager->addErrorMessage(
                    __('Something went wrong while saving the item data. Please review the error log.')
                );
                $this->_objectManager->get('Psr\Log\LoggerInterface')->critical($e);
                $this->_objectManager->get('Magento\Backend\Model\Session')->setPageData($data);
                $this->_redirect('cat_offerpage/*/edit', ['id' => $this->getRequest()->getParam('offerpage_id')]);
                return;
            }
        }
        $this->_redirect('cat_offerpage/*/');
    }
}
