stage:
    deploy:
        MYSQL_USE_SLAVE_CONNECTION: true
        REDIS_USE_SLAVE_CONNECTION: true
        REDIS_BACKEND: '\Magento\Framework\Cache\Backend\RemoteSynchronizedCache'
        CRON_CONSUMERS_RUNNER:
            cron_run: true
            max_messages: 1000
            consumers: []
    build:
        SCD_MATRIX:
            "Magento/luma": []
        SCD_MAX_EXECUTION_TIME: 3600
        SCD_COMPRESSION_TIMEOUT: 800
        QUALITY_PATCHES:
          - MDVA-31969
