# this file will create the "web" image, it is a Nginx image + app files generated the same way as the app files in the "app" image
FROM magento/magento-cloud-docker-php:7.3-fpm-1.3.0 as builder
WORKDIR /var/www/html
# copy composer files from php composer version 1 official image
COPY --from=composer:1 /usr/bin/composer /usr/bin/composer
# copy php composer related files from the building directory
COPY --chown=www-data composer.json composer.json
COPY --chown=www-data composer.lock composer.lock
COPY --chown=www-data auth.json auth.json
# speedup composer install with prestissimo since we cant use composer 2
RUN composer global require hirak/prestissimo
RUN composer install --no-dev --ansi --ignore-platform-reqs
# copy custom files to code and design directories
COPY app/code/ app/code/
COPY app/design/ app/design/
# set the production mode for magento
ENV MAGE_MODE=production
# update composer autoloade file
RUN composer dump-autoload --optimize --apcu
# copy the build configuration file
COPY app/etc/config.php app/etc/config.php
# execute the required magento commands
RUN bin/magento setup:di:compile
RUN bin/magento setup:static-content:deploy en_US ar_SA -j 12
COPY app/etc/env.php app/etc/env.php



# the "web" image will be used to run the Nginx server
FROM magento/magento-cloud-docker-nginx:1.19-1.2.4 as web
#copy the app files from the builder image
#TODO: create the files directly in /app and resolve the permission issues with composer
COPY --from=builder /var/www/html /app