<div class="fieldset-wrapper customer-information send-pushnotification">

    <input type="hidden" name="sendnotificationurl" value="<?= /* @noEscape */ $this->getUrl('ktpl_pushnotification/ktplpushnotifications/sendbycustomerview');?>">

    <input type="hidden" name="send_to_customer" value="<?= /* @noEscape */ $block->getCustomerEmail();?>">

        <button id="send_notification" title="Send Notifiation" type="button" class="send-push-notification-to-this-customer action-basic" href="#" data-form-role="save" data-ui-id="save-button" role="button" aria-disabled="false"><span class="ui-button-text" style="float: right;">
            <span>Send Notification</span>
        </span></button>
 
</div>

<style type="text/css">
    button#send_notification{        
        margin-left: 231px;
    }
</style>
