<?php
 /**
  * Magedelight
  * Copyright (C) 2019 Magedelight <info@magedelight.com>
  *
  * @category Magedelight
  * @package Magedelight_ConfigurableProduct
  * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
  * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
  * @author Magedelight <info@magedelight.com>
  */
 /** @var $block \Magedelight\ConfigurableProduct\Block\Product\View\Type\Renderer\Configurable */
?>
<div class="swatch-opt" data-role="swatch-options"></div>
<script type="text/x-magento-init">
    {
        "[data-role=swatch-options]": {
            "Magedelight_ConfigurableProduct/js/rb-swatch-renderer": {
                "jsonConfig": <?= /* @noEscape */ $swatchOptions = $block->getJsonConfig() ?>,
                "jsonSwatchConfig": <?= /* @noEscape */ $swatchOptions = $block->getJsonSwatchConfig(); ?>,
                "mediaCallback": "<?= /* @noEscape */ $block->getMediaCallback() ?>",
                "gallerySwitchStrategy": "<?= $block->getVar(
                    'gallery_switch_strategy',
                    'Magento_ConfigurableProduct'
                ) ?: 'replace'; ?>",
                "jsonSwatchImageSizeConfig": <?= /* @noEscape */ $block->getJsonSwatchSizeConfig() ?>
            }
        },
        "*" : {
            "Magento_Swatches/js/catalog-add-to-cart": {}
        }
    }
</script>