apiVersion: v1
kind: Pod
metadata:
  namespace: infra
spec:
  securityContext:
    fsGroup: 1000
  containers:
    - name: pipeline
      image: busybox:latest
      imagePullPolicy: IfNotPresent
      command:
        - cat
      tty: true
      resources:
        limits:
          memory: "2Gi"
        requests:
          cpu: "2"
          memory: "2Gi"
