<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_ProductAlert
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<?php $registry = $this->_helperFactory->get('Magento\Framework\Registry'); ?>
<?php $_productId = $registry->registry('product')->getId() ?>
<?php $helper = $this->helper('Magedelight\ProductAlert\Helper\Data'); ?>
<?php $urlHelper = $this->helper('Magento\Framework\Url\Helper\Data'); ?>
<?php $url = $block->escapeHtml($helper->getEmailUrl('stock')); ?>
<?php $_productId = $registry->registry('product')->getId() ?>
<script type="text/javascript">
    require([
        'jquery',
        "mage/mage",
        "mage/validation"
    ], function ($) {
        "use strict";
        $('#form-validate-stock').mage('validation');
    });
</script>

<div class="rb-block">
    <form id="form-validate-stock" method="post" action="<?php echo $url; ?>">
        <label>
            <?php echo __('Notify me to back in stock notification'); ?>
        </label
        >
        <input name="guest_email"
               class="input-text md_guest_email"
               id="md_guest_email-<?php echo $_productId; ?>"
               size="30"
               type="email"
               data-validate="{required:true, 'validate-email':true}"
           placeholder="<?= __('Please enter your email') ?>"
        />
        <input type="hidden" name="product_id" value="<?php echo $_productId; ?>"/>
        <input type="hidden" name="type" value="email"/>
        <input type="hidden" name="parent_id"
               value="<?php echo $registry->registry('par_product_id') ?>"/>
        <input type="hidden"
               name="<?php echo \Magento\Framework\App\Action\Action::PARAM_NAME_URL_ENCODED ?>"
               value="<?php echo $urlHelper->getEncodedUrl() ?>"/>

        <div class="actions-toolbar md_guest_action">
            <div class="primary">
                <button type="submit" class="action submit primary">
                    <span><?php echo __('Notify Me'); ?></span>
                </button>
            </div>
        </div>
    </form>
</div>   
 
