<?php
/**
 * KrishTechnolabs
 *
 * PHP version 7
 *
 * @category  KrishTechnolabs
 * @package   Ktpl_ElasticSearch
 * @author    Dhara Bhatti <dhara.bhatti@krishtechnolabs.com>
 * @copyright 2019 (c) KrishTechnolabs (https://www.KrishTechnolabs.com/)
 * @license   https://www.krishtechnolabs.com/LICENSE.txt Krish License
 * @link      https://www.krishtechnolabs.com/
 */
?>

<?php
//@codingStandardsIgnoreFile
/** @var \Ktpl\ElasticSearch\Block\Index\Base $block */

/** @var \Magefan\Blog\Block\Post\PostList\Item $postItem */
$postItem = $this->getLayout()->createBlock('\Magefan\Blog\Block\Post\PostList\Item');
?>
<div class="ktpl-search__index ktpl-search__index-magefan-blog-post">
    <div class="post-list-wrapper">
        <ol class="post-list">
            <?php /** @var \Magefan\Blog\Model\Post $post */ ?>
            <?php foreach ($block->getCollection() as $post): ?>
                <li>
                    <?= $postItem
                        ->setPost($post)
                        ->setTemplate('post/list/item.phtml')
                        ->toHtml()
                    ?>
                </li>
            <?php endforeach ?>
        </ol>
    </div>
</div>
