<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Catalog
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
 /** @var $block \Magedelight\Catalog\Block\Product\Nonlive */
?>

<?php
$nonlivestatus = $this->getRequest()->getParam('vpro');
$session = $block->getSessionForGrid();
$gridsession = $session->getGridSession();
$helper = $this->helper('Magedelight\Catalog\Helper\Listing\Data');
$canSetSearchValue = ($this->getRequest()->getParam('sfrm') == 'nl') ? true : false;

if ($nonlivestatus == "pending") {
    $product_nonlive = $gridsession['grid_session']['product_nonlive_pending'];
} elseif ($nonlivestatus == "approve") {
    $product_nonlive = $gridsession['grid_session']['product_nonlive_approved'];
} else {
    $product_nonlive = $gridsession['grid_session']['product_nonlive_disaaproved'];
}

?>

<?php
$reqParams = $this->getRequest()->getParams();
if (array_key_exists('sfrm', $reqParams)) {
    unset($reqParams['p']);
    if ($reqParams['sfrm'] == 'l') {
        unset($reqParams['limit']);
        unset($reqParams['sort_order']);
        unset($reqParams['dir']);
    }
}
$reqParams['sfrm'] = 'nl';
$reqParams['p'] = '1';
if (!array_key_exists('vpro', $reqParams)) {
    $reqParams['vpro'] = 'approve';
}
?>
<div id="non-live-search-form-row" class="row non-live">
    <div class="row-gutter toolbar-wrapper mb10">
        <div class="col-xs-4">
            <form id="non-live-search-form" method="get" enctype='multipart/form-data' action="<?= $helper->getResultUrl(); ?>" data-hasrequired="<?= __('* Required Fields') ?>" data-mage-init='{"validation":{}}'>
                <?php foreach ($reqParams as $pKey => $pvalue) { ?>
                    <?php
                    if ($pKey == 'ostock' || $pKey == 'q') {
                        continue;
                    } ?>
                    <input type="hidden" name="<?= $pKey; ?>" value="<?= $pvalue; ?>"/>
                <?php } ?>
                <div class="block block-search">
                    <div class="content">
                        <div class="field search-catalog">
                            <div class="control">
                                 <?php 
                                if ($product_nonlive['q']) {
                                      $value = $product_nonlive['q'];
                                 } else {
                                      $value = $canSetSearchValue ? $helper->searchText() : ''; 
                                }
                                 ?>
                                <input placeholder="<?= __('Product Name, Vendor SKU...') ?>" type="text" value="<?= htmlspecialchars($value, ENT_QUOTES, 'UTF-8'); ?>" name="<?= $helper->getQueryParamName() ?>" class="input-text search-catalog-input" id="search-catalog-input" />
                            </div>
                            <div class="actions">
                                <div class="vendor primary"><button type="submit" class="vendor action login primary"><span><?= __('Search') ?></span></button></div>
                            </div>
                        </div>
                    </div>
                </div>
                <input type="hidden" name="session-clear-product-nonlive" id="session-clear-product-nonlive" value="0"/>
            </form>
        </div>
        <div class="col-xs-8">
            <div class="row">
                <div class="col-xs-2 pt10">
                    <a rel="nl" href="javascript:void(0)" class="action-default reset-nonlive"><?= __('Reset') ?></a>
                </div>
                <div class="col-xs-10">
                    <div class="toolbar-filter-wrapper">
                        <div class="topbar-left col-xs-12 pt5 text-right">  
                            <div class="product-filter-status" data-bind="collapsible">
                              <span class="filter-btn" data-bind="toggleCollapsible"><?= __('Filter') ?></span>
                              <ul class="product-filter-status-dropdown" data-bind="css: {_active: $collapsible.opened}">
                                <span class="pull-left filter-label">Product Status</span>
                                <li><a id="status_approve" href="<?= $block->getParamUrl('approve'); ?>"  title="" class="status approve"><?= __('Approved') ?></a></li>
                                <li><a id="status_pending" href="<?= $block->getParamUrl('pending') ?>"  title="" class="status pending"><?= __('Pending') ?></a></li>
                                <li><a id="status_disapproved" href="<?= $block->getParamUrl('disapproved') ?>" title="" class="status disapproved"><?= __('Disapproved') ?></a></li>
                              </ul>
                          </div> 
                          <div class="data-grid-filters-actions-wrap ml10">
                            <div class="data-grid-filters-action-wrap">
                                <a class="action export" href="<?= $block->getUrl('*/*/exportNonLiveProducts', ['_current' => true])
                                ?>"><?= __('Export') ?></a>
                            </div>
                          </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <script type="text/javascript">
            require(['jquery'], function ($) {
                <?php
                switch ($nonlivestatus) {
                    case 'approve':
                        ?>
                        <?= '$("#status_approve").addClass("active");'; ?>
                        <?php
                        break;
                    case 'pending':
                        ?>
                        <?= '$("#status_pending").addClass("active");'; ?>
                        <?php
                        break;
                    case 'disapproved':
                        ?>
                        <?= '$("#status_disapproved").addClass("active");'; ?>
                        <?php
                        break;
                    default:
                        ?>
                        <?= '$("#status_approve").addClass("active");'; ?>
                        <?php
                        break;
                }
                ?>
            });
        </script>
    </div>
</div>

<?php if ($nonlivestatus == null || ($nonlivestatus == 'approve')) { ?>
    <?= $this->getChildHtml('nonlive.approved'); ?>
<?php } elseif ($nonlivestatus == 'pending') { ?>
    <?= $this->getChildHtml('nonlive.pending'); ?>
<?php } elseif ($nonlivestatus == 'disapproved') { ?>
    <?= $this->getChildHtml('nonlive.disapproved'); ?>
<?php } ?>