<?php
/**
 * KrishTechnolabs
 *
 * PHP version 7
 *
 * @category  KrishTechnolabs
 * @package   Ktpl_ElasticSearch
 * @author    Dhara Bhatti <dhara.bhatti@krishtechnolabs.com>
 * @copyright 2019 (c) KrishTechnolabs (https://www.KrishTechnolabs.com/)
 * @license   https://www.krishtechnolabs.com/LICENSE.txt Krish License
 * @link      https://www.krishtechnolabs.com/
 */
?>
<script type="text/javascript">

    function func_<?= $this->getHtmlId() ?>() {
        var elem = $('btn_<?= $this->getHtmlId() ?>');
        var params = {};

        new Ajax.Request('<?= $this->getAjaxUrl() ?>', {
            parameters: params,
            onSuccess: function (transport) {
                var result = transport.responseText.evalJSON();

                $('result_<?= $this->getHtmlId() ?>')
                    .update('<strong>' + result.message + '</strong><br>'
                        + '<small><pre>' + result.note + '</pre></small>')
                    .show();

                if (result.success == true) {
                    $('result_<?= $this->getHtmlId() ?>').removeClassName('message-error');
                    $('result_<?= $this->getHtmlId() ?>').addClassName('message-success');
                } else {
                    $('result_<?= $this->getHtmlId() ?>').removeClassName('message-success');
                    $('result_<?= $this->getHtmlId() ?>').addClassName('message-error');
                }
            },
            onComplete: function (response) {
                if (403 == response.status) {
                    $('result_<?= $this->getHtmlId() ?>')
                        .update('Access denied')
                        .show();
                    $('result_<?= $this->getHtmlId() ?>').removeClassName('message-success');
                    $('result_<?= $this->getHtmlId() ?>').addClassName('message-error');
                }
            }

        });
    }

</script>
<button onclick="func_<?= $this->getHtmlId() ?>(); return false;" class="scalable" type="button"
        id="<?= $this->getHtmlId() ?>">
    <span><?= $this->escapeHtml($this->getButtonLabel()) ?></span>
</button>

<ul id="result_<?= $this->getHtmlId() ?>" style="display:none; max-width: 400px; max-height: 400px;overflow: scroll;" class="message"></ul>