<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Product\View */
?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()): ?>
<div class="mobile-button-stickybox">
    <div class="qty-box">
        <?php if ($block->shouldRenderQuantity()): ?>
        <div class="field qty">
            <label class="label" for="qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></label>
                
                <div class="control" data-bind="scope: 'qty_change'">
         
                    <button data-bind="click: decreaseQty">-</button>
                 
                    <input  data-bind="value: qty()"
                            type="number"
                            name="qty"
                            id="qty"
                            maxlength="12"
                            title="<?php /* @escapeNotVerified */ echo __('Qty') ?>" class="input-text qty"
                            data-validate="<?php echo $block->escapeHtml(json_encode($block->getQuantityValidators())) ?>"
                    />
                 
                    <button data-bind="click: increaseQty">+</button>
                </div>
        
        </div>
        <?php endif; ?>
    </div>
    <div class="box-tocart">
        <div class="fieldset">
            <div class="actions">
                <button type="submit"
                        title="<?= /* @escapeNotVerified */ $buttonTitle ?>"
                        class="action primary tocart"
                        id="product-addtocart-button" disabled>
                    <span><?= /* @escapeNotVerified */ $buttonTitle ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>

                <?php $productId = $block->getProduct()->getId(); ?>
                <div id="wishlist_<?php echo $productId; ?>" class="action wishlist-box" data-bind="scope:'wishlist_<?php echo $productId; ?>'">
                    <!-- ko template: getTemplate() --><!-- /ko -->
                </div>
            </div>

            
        </div>
    </div>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }
</script>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "qty_change": {
                        "component": "Magento_Catalog/js/qty_change",
                        "defaultQty": <?php echo $block->getProductDefaultQty() * 1 ?>
                    }
                 }
            }
        }
    }
</script>