<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
$loggedIn = $this->helper('\Magedelight\Theme\Helper\Data')->isCustomerLogIn();
?>
<?php if ($block->isPossibleOnepageCheckout()):?>
        <?php if ($loggedIn) : ?>
            <button type="button"
                    data-role="proceed-to-checkout"
                    title="<?= /* @escapeNotVerified */ __('Proceed to Checkout') ?>"
                    data-mage-init='{"Magento_Checkout/js/proceed-to-checkout":{"checkoutUrl":"<?= /* @escapeNotVerified */ $block->getCheckoutUrl() ?>"}}'
                    class="action primary checkout<?= ($block->isDisabled()) ? ' disabled' : '' ?>"
                    <?php if ($block->isDisabled()):?>disabled="disabled"<?php endif; ?>>
                <span><?= /* @escapeNotVerified */ __('Proceed to Checkout') ?></span>
            </button>
        <?php else : ?>
    	    <li class="authorization-link md-custom-toplink" data-label="<?php echo $block->escapeHtml(__('or')); ?>">
    	        <a href="javascript:void(0)" id="md-signin-link" class="md-login-form">
    	            <span><?= /* @escapeNotVerified */ __('Proceed to Checkout') ?></span>
    	        </a>
    	    </li>
        <?php endif; ?>
<?php endif?>
