<?php
/**
 * Magedelight
 * Copyright (C) 2018 Magedelight <info@magedelight.com>.
 *
 * NOTICE OF LICENSE
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see http://opensource.org/licenses/gpl-3.0.html.
 *
 * @category Magedelight
 * @package Magedelight_SocialLogin
 * @copyright Copyright (c) 2018 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<?php
$position = $block->getDisplayPosition();

if (!$block->isLoggedIn()) :  ?>

    <li class="authorization-link md-custom-toplink" data-label="<?php echo $block->escapeHtml(__('or')); ?>">
        <a href="javascript:void(0)" id="md-signin-link" class="md-login-form" >
            <?php echo $block->escapeHtml($block->getLabel()); ?>
        </a>
    </li>
    <li class="register-link md-custom-toplink">
        <a href="javascript:void(0)" id="md-register-link" class="md-create-user">
            <?php /* @noEscape */ echo __('Create an Account');?></a>
    </li>
    <?php if ($position == 'top' || $position == 'left') : ?>
        <div id='md_popup' style='display:none;' class="<?php echo $position ?>">

            <?php echo $block->getChildHtml('md.customer.sociallogin'); ?>

            <div id='md-login-form'>
                <?php echo $block->getChildHtml('md.customer.login');
                echo $block->getChildHtml('md.customer.forgot'); ?>
            </div>
            <?php echo $block->getChildHtml('md.customer.register'); ?>
        </div>
    <?php else : ?>
        <div id='md_popup' style='display:none;' class="<?php echo $position ?>">
            <div id='md-login-form'>
                <?php echo $block->getChildHtml('md.customer.login');
                echo $block->getChildHtml('md.customer.forgot'); ?>
            </div>
            <?php echo $block->getChildHtml('md.customer.register'); ?>
            <?php echo $block->getChildHtml('md.customer.sociallogin'); ?>

        </div>
    <?php endif;
endif;
?>
<script type="text/x-magento-init">
    {
        "*": {
            "Magedelight_SocialLogin/js/reload-customer":{}
        }
    }
</script>