<?php $buttonTitle = __('Go To Product');?>
<div class="box-gotoproduct">
    <div class="fieldset">
        <div class="actions">
            <a target="_parent" href="<?php /* @noEscape */ echo $this->getProduct()->getProductUrl() ?>" title="<?php /* @noEscape */ echo __($buttonTitle) ?>" class="action primary" id="product-gotoproduct-button">
                <span><?php /* @noEscape */ echo __($buttonTitle) ?></span>
            </a>
        </div>
    </div>
</div>