<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Shippingmatrix
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<?php /** #var $block Magedelight\Vendor\Block\Orde\Cancelgrid */ ?>
<?php
$_matrixrates = $block->getMatrixRateCollection();
$matrixRate = $block->getMatrixRate();
$condition_label = $block->getShippingMatrixConditionLabel();
$conditionName = $block->getShippingMatrixCondition();
?>
<div class="row">
        <div class="row-gutter toolbar-wrapper mb10">
        <div class="col-xs-3">
          <div class="topbar-left">
            <div class="data-grid-filters-action-wrap">
                <a class="action secondary action-default _active export" href="<?php echo $block->getUrl('*/*/exportPost', ['_current' => true])?>">
                    <span><?php echo __('Export') ?></span>
                </a>
                <a href="javascript:void(0)" data-href="<?php echo $this->getUrl("rbshippingmatrix/guidelines") ?>" class="action rbshippingmatrix-guidelines">
                    <?php echo __("Help") ?>
                </a>
            </div>
          </div>
        </div>
        <div class="col-xs-9">
          <div class="topbar-right">
              <div class="data-grid-filters-action-wrap">
                  <div class="data-grid-filters-action-wrap">
                      <form id="import-form" class="" action="<?php /* @escapeNotVerified */ echo $block->getUrl('*/*/importPost') ?>" method="post" enctype="multipart/form-data">
                      <fieldset class="fieldset">
                          <div class="field">
                              <input type="file" id="import_rates_file" name="import_rates_file" class="inputfile inputfile-1" accept=".csv"/>
                              <label for="import_rates_file"><span><?php echo __('Choose a file')?></span></label>
                              <span><?php echo __('Only .CSV can upload');?></span>
                        </div>
                        </fieldset>
                          <button class="action secondary action-default _active import" type="submit" data-action="grid-filter-expand" title="Import Csv">
                              <span><?php echo __('Import Csv') ?></span>
                          </button>
                      </form>
                  </div>
              </div>
            </div>
       </div>
    </div>
</div>

<div class="table-wrapper orders-history">
    <form name="matrix_rate_form"
                  id="matrix_rate_form"
                  method="post" 
                  action=""
                  data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" 
                  data-mage-init='{"validation":{}}'>
        <table class="data table table-order-items history" id="matrix-rate-table-form">

            <caption class="table-caption"><?php echo __('Matrix Rates') ?></caption>
            <thead>
                <tr id="matrix-rate-form">
                    <th scope="col" sortorder="" class="col shipping sortable"><?php echo __('Country') ?></th>
                    <th scope="col" sortorder="" class="col shipping sortable"><?php echo __('Region') ?></th>
                    <th scope="col" sortorder="" class="col shipping sortable"><?php echo __('City') ?></th>
                    <th scope="col" sortorder="" class="col shipping sortable"><?php echo __('Zipcode From *') ?></th>
                    <th scope="col" sortorder="" class="col shipping sortable"><?php echo __('Zipcode To *') ?></th>
                    <th scope="col" sortorder="" class="col shipping sortable">
                        <?php echo $condition_label['condition_from']; ?>
                        <?php if ($conditionName == 'package_weight') :
                            ?><?php echo '('.$block->weightUnit().')';?><?php
                        endif;?>
                    </th>
                    <th scope="col" sortorder="" class="col shipping sortable">
                        <?php echo $condition_label['condition_to']; ?>
                        <?php if ($conditionName == 'package_weight') :
                            ?><?php echo '('.$block->weightUnit().')';?><?php
                        endif;?>
                    </th>
                    <th scope="col" sortorder="" class="col shipping sortable"><?php echo __('Price') ?></th>
                    <th scope="col" sortorder="" class="col shipping sortable"><?php echo __('Shipping Method') ?></th>
                    <th scope="col" class="col actions"><?php echo __('Action') ?></th>
                </tr>
            </thead>
            <tbody>
            
                <input class="input-text required-entry"
                       type="hidden"
                       name="pk"
                       id="pk"
                       value = "<?php echo @$matrixRate['pk']; ?>"/>
                <input class="input-text required-entry"
                       type="hidden"
                       name="vendor_id"
                       id="vendor_id"
                       value = "<?php echo @$matrixRate['vendor_id']; ?>"
                       data-validate="{required:true}"/>
                <input class="input-text required-entry"
                       type="hidden"
                       name="condition_name"
                       id="condition_name"
                       value = "<?php echo $block->getShippingMatrixCondition(); ?>"
                       data-validate="{required:true}"/>
                <tr if="table-form">
                    <td class="col data-grid-date-cell">
                    <div class="data-grid-cell-content">
                        <select name="dest_country_id" id="dest_country_id" data-validate="{required:true}">
                            <option value="0"><?php echo __('All');?></option>
                            <?php foreach ($block->getCountryCollection() as $country) : ?>
                                <option value="<?php echo $country['country_id']; ?>">
                                    <?php echo $country['country_name']; ?></option>
                            <?php endforeach; ?>
                        </select>
                        </div>
                    </td>
                    <td class="col data-grid-date-cell">
                    <div class="data-grid-cell-content">
                        <select name="dest_region_id" id="dest_region_id" data-validate="{required:true}">
                            <option value="0"><?php echo __('All');?></option>
                        </select>
                        </div>
                    </td>                    
                    <td class="col data-grid-date-cell">
                    <div class="data-grid-cell-content">
                        <input class="input-text required-entry"
                            type="text"
                            id="dest_city"
                            name="dest_city"
                            value = "<?php echo (isset($matrixRate['dest_city'])) ? @$matrixRate['dest_city'] : '*'?>"
                            data-validate="{required:true}"
                            placeholder="<?php echo __('City'); ?>"/>
                            </div>
                    </td>                    
                    <td class="col data-grid-date-cell">
                    <div class="data-grid-cell-content">
                        <input class="input-text required-entry"
                               type="text"
                               id="dest_zip"
                               name="dest_zip"
                               value = "<?php echo (isset($matrixRate['dest_zip'])) ? @$matrixRate['dest_zip'] : '*' ?>"
                               data-validate="{required:true}"
                               placeholder="<?php echo __('From'); ?>"/>
                           <!--<div class="note"><span>* is for all Zipcode.</span></div>-->
                           </div>
                    </td>
                    <td class="col data-grid-date-cell">
                    <div class="data-grid-cell-content">
                        <input class="input-text required-entry"
                               type="text"
                               id="dest_zip_to"
                               name="dest_zip_to"
                               value = "<?php echo (isset($matrixRate['dest_zip_to'])) ? @$matrixRate['dest_zip_to'] : '*' ?>"
                               data-validate="{required:true}"
                               placeholder="<?php echo __('To'); ?>"/>
                           <!--<div class="note"><span>* is for all Zipcode.</span></div>-->
                           </div>
                    </td>
                    <td class="col data-grid-date-cell">
                    <div class="data-grid-cell-content">
                        <div class="field vendor-sku required">
                            <div class="control">
                                <input class="input-text required-entry validate-not-negative-number"
                                       type="number"
                                       id="condition_from_value"
                                       name="condition_from_value"
                                       value = "<?php echo @$matrixRate['condition_from_value']; ?>"
                                       data-validate="{required:true}"
                                       min="1"
                                       placeholder="<?php echo __('From'); ?>"/>
                            </div>
                        </div>
                        </div>
                    </td>
                    <td class="col data-grid-date-cell">
                    <div class="data-grid-cell-content">
                        <input class="input-text required-entry validate-not-negative-number"
                               type="number"
                               id="condition_to_value"
                               name="condition_to_value"
                               value = "<?php echo @$matrixRate['condition_to_value']; ?>"
                               data-validate="{required:true}"
                               min="1"
                               placeholder="<?php echo __('To'); ?>"/>
                        </div>
                    </td>
                    <td class="col data-grid-date-cell">
                    <div class="data-grid-cell-content">
                        <input class="input-text required-entry validate-not-negative-number"
                               type="number"
                               id="price"
                               name="price"
                               value = "<?php echo @$matrixRate['price']; ?>"
                               data-validate="{required:true}"
                               placeholder="<?php echo __('Price'); ?>"/>
                        </div>
                    </td>
                    <td class="col data-grid-date-cell">
                    <div class="data-grid-cell-content">
                        <select name="shipping_method" id="shipping-method" data-validate="{required:true}">                            
                            <?php foreach ($block->getShippingMethods() as $shippingMethod) : ?>
                                <option value="<?php echo $shippingMethod['value']; ?>">
                                    <?php echo $shippingMethod['label']; ?></option>
                            <?php endforeach; ?>
                        </select>
                        </div>
                    </td>
                    <td class="col data-grid-actions-cell">
                    <div class="data-grid-cell-content">
                        <button type="button"
                                id ="submit"
                                name ="submit"
                                class="action button primary">
                            <span id='savebtn'><?php echo __('Add') ?></span>
                        </button>
                        <button type="button"
                                id ="cancel"
                                name ="cancel"
                                class="action button primary cancel">
                            <span id='cancel'><?php echo __('Cancel') ?></span>
                        </button>
                        </div>
                    </td>
                </tr>
            </tbody>
        </table>
    </form>
</div>
    <div class="table-wrapper orders-history mb30">
        <table class="data table table-order-items history" id="matrix-rate-table">
            <caption class="table-caption"><?php echo __('Matrix Rates') ?></caption>
            <thead>
                <tr id="matrix-rate-form">
                    <th scope="col" sortorder="" class="col id sortable"><?php echo __('ID #') ?></th>
                    <th scope="col" sortorder="" class="col shipping sortable"><?php echo __('Country') ?></th>
                    <th scope="col" sortorder="" class="col shipping sortable"><?php echo __('Region') ?></th>
                    <th scope="col" sortorder="" class="col shipping sortable"><?php echo __('City') ?></th>
                    <th scope="col" sortorder="" class="col shipping sortable"><?php echo __('Zipcode From') ?></th>
                    <th scope="col" sortorder="" class="col shipping sortable"><?php echo __('Zipcode To') ?></th>
                    <th scope="col" sortorder="" class="col shipping sortable">
                        <?php echo __($condition_label['condition_from']); ?>
                        <?php if ($conditionName == 'package_weight') :
                            ?><?php echo __('('.$block->weightUnit().')');?><?php
                        endif;?>
                    </th>
                    <th scope="col" sortorder="" class="col shipping sortable">
                        <?php echo __($condition_label['condition_to']); ?>
                        <?php if ($conditionName == 'package_weight') :
                            ?><?php echo __('('.$block->weightUnit().')');?><?php
                        endif;?>
                    </th>
                    <th scope="col" sortorder="" class="col shipping sortable"><?php echo __('Price') ?></th>
                    <th scope="col" sortorder="" class="col shipping sortable"><?php echo __('Shipping Method') ?></th>
                    <th scope="col" class="col actions"><?php echo __('Action') ?></th>
                </tr>
            </thead>
            <tbody>
                
                <?php if ($_matrixrates && count($_matrixrates)) : ?>
                    <?php foreach ($_matrixrates as $_matrixrate) : ?>
                        <tr class="row-<?php echo $_matrixrate['pk'] ?>">
                            <td data-th="<?php echo $block->escapeHtml(__('ID #')) ?>" class="col data-grid-id-cell rate-id">
                                <div class="data-grid-cell-content rate-display-id">
                                    <?php echo $_matrixrate['pk'] ?>
                                </div>
                            </td>
                            <td data-th="<?php echo $block->escapeHtml(__('Country')) ?>" class="col data-grid-country country-id">
                              <div class="data-grid-cell-content">
                            <?php if ($_matrixrate['dest_country_id'] == '0') {
                                echo __('All');
                            } else {
                                echo $block->getCountryName($_matrixrate['dest_country_id']);
                            } ?>
                              </div>
                            </td>
                            <td data-th="<?php echo $block->escapeHtml(__('Region')) ?>" class="col data-grid-region">
                                <div class="data-grid-cell-content">
                            <?php if ($_matrixrate['dest_region_id'] == '0') {
                                echo __('All');
                            } else {
                                echo $block->getRegionName($_matrixrate['dest_region_id']);
                            } ?>
                              </div>
                            </td>
                            <td data-th="<?php echo $block->escapeHtml(__('City')) ?>" class="col data-grid-dest-city">
                            <div class="data-grid-cell-content">
                                <?php echo $_matrixrate['dest_city'] ?>
                              </div>

                            </td>
                            <td data-th="<?php echo $block->escapeHtml(__('Zipcode From')) ?>" class="col data-grid-dest-zip">
                            <div class="data-grid-cell-content">
                                <?php echo $_matrixrate['dest_zip'] ?>
                            </div>
                              </td>
                            <td data-th="<?php echo $block->escapeHtml(__('Zipcode To')) ?>" class="col data-grid-dest-zip-to">
                              <div class="data-grid-cell-content">
                                <?php echo $_matrixrate['dest_zip_to'] ?>
                                </div>
                            </td>
                            <td data-th="<?php echo $block->escapeHtml(__('Condition From')) ?>" class="col data-grid-condition-from">
                                <div class="data-grid-cell-content">
                                <?php if ($conditionName == 'package_weight') :?>
                                    <?php echo $_matrixrate['condition_from_value'];?>
                                    <?php echo '('.$block->weightUnit().')';?>
                                <?php else :?>
                                    <?php if ($conditionName == 'package_value') :?>
                                        <?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($_matrixrate['condition_from_value']);?>
                                    <?php endif;?>
                                    <?php if ($conditionName == 'package_qty') :?>
                                        <?php echo $_matrixrate['condition_from_value'];?>
                                    <?php endif;?>
                                <?php endif;?>
                                </div>
                            </td>
                            <td data-th="<?php echo $block->escapeHtml(__('Condition To')) ?>" class="col data-grid-condition-to">
                                <div class="data-grid-cell-content">
                                <?php if ($conditionName == 'package_weight') :?>
                                    <?php echo $_matrixrate['condition_to_value'];?>
                                    <?php echo '('.$block->weightUnit().')';?>
                                <?php else :?>
                                    <?php if ($conditionName == 'package_value') :?>
                                        <?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($_matrixrate['condition_to_value']);?>
                                    <?php endif;?>
                                    <?php if ($conditionName == 'package_qty') :?>
                                        <?php echo $_matrixrate['condition_to_value'];?>
                                    <?php endif;?>
                                <?php endif;?>
                                </div>
                            </td>
                            <td data-th="<?php echo $block->escapeHtml(__('Price')) ?>" class="col data-grid-price">
                              <div class="data-grid-cell-content">
                                <?php echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($_matrixrate['price']); ?>
                              </div>
                            </td>
                            <td data-th="<?php echo $block->escapeHtml(__('Shipping Method')) ?>" class="col data-grid-shipping-method">
                                  <div class="data-grid-cell-content">
                            <?php echo __($block->getShippingMethodNameById($_matrixrate['shipping_method'])); ?>
                              </div>
                            </td>
                            <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="col data-grid-actions-cell">
                            <div class="data-grid-cell-content">
                                <a href="javascript:void(0);" class="action view editbtn">
                                    <span><?php echo __('Edit') ?></span>
                                </a>
                                <a href="javascript:void(0)" data-url="<?php echo $block->getDeletePostActionUrl($_matrixrate['pk']); ?>" class="action delete deletebtn">
                                    <span><?php echo __('Delete') ?></span>
                                </a>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php else : ?>
                    <tr id="message-info-shipping-rate">
                        <td colspan="100" style="text-align: center">
                            <div id="cancelorder-msg" class="message info empty">We couldn't find any records.</div>
                        </td>
                    </tr>
                <?php endif; ?>

            </tbody>
        </table>
    <?php /*<div class="note"><b> <?php echo __('Note');?>:- </b><?php echo __("In Zipcode Column '*' - matches any; 'xyz*' - matches any that begins on 'xyz' and are not longer than 10.");?></div> */?>
    </div>
<?php if ($block->getPagerHtml()) : ?>
    <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif ?>

<div id="shipping_rates_modal_popup"></div>

<script type="text/javascript">
    require([
        'jquery',
        'Magento_Ui/js/modal/alert',
        'Magento_Ui/js/modal/confirm',
        'Magento_Ui/js/modal/modal'
    ], function ($, alert, confirmation, modal) {
        $(document).on('change', '#dest_country_id', function () {
            getRegion($('#dest_country_id').val());
        });
        $(document).ready(function () {
            $('#dest_city,#dest_zip,#dest_zip_to').on('focus', function () {
                if (!$(this).data('defaultText'))
                    $(this).data('defaultText', $(this).val());
                if ($(this).val() == $(this).data('defaultText'))
                    $(this).val('');
            });
            $('#dest_city,#dest_zip,#dest_zip_to').on('blur', function () {
                if ($(this).val() == '')
                    $(this).val($(this).data('defaultText'));
            });
            
            <?php if ($conditionName == 'package_qty') : ?>
            $('#condition_from_value').on('change',function(event){
                if($("#condition_from_value").val() == 0){
                    $("#condition_from_value").val('1');
                }
            });
            
            $('#condition_to_value').on('change',function(event){
                if($("#condition_to_value").val() == 0){
                    $("#condition_to_value").val('1');
                }
            });
            <?php endif;?>
                
            $(document).on("click", "#submit" , function() {
                if($('#matrix_rate_form').valid()){
                if (parseFloat($("#condition_from_value").val()) >= parseFloat($("#condition_to_value").val())) {
                    alert({
                        content: $.mage.__("Order Subtotal To value always higher than Order Subtotal From value.")
                    });
                    $("#condition_to_value").focus();
                    return false;
                }                
                
                var url = "<?php echo $this->getUrl($block->getSavePostActionUrl()); ?>";
                var data = $('#matrix_rate_form').serialize();
                var html = '';
                $.ajax({
                    url: url,
                    showLoader: true,
                    data: data,
                    type: 'POST',
                    success: function (data) {
                        var options = {
                          type: 'popup',
                          responsive: true,
                          buttons: [{
                                  text: "<?php echo __('Close') ?>",
                                  class: '',
                                  click: function () {
                                      this.closeModal();
                                  }
                              }]
                        };
                        if(data.error){
                            $("#shipping_rates_modal_popup").html(data.error);
                            var popup = modal(options, $('#shipping_rates_modal_popup'));
                            $("#shipping_rates_modal_popup").modal('openModal');
                            return false;
                        }
                        
                        
                        if ($("tr.row-"+data['pk']).attr("class") == undefined) {
                            html += "<tr class='row-" + data['pk'] + "'>";
                        }
                        html += "<td class='col data-grid-id-cell rate-display-id'>" + data['pk'] + "</td>\n\
                           <td class='col data-grid-country country-id'>" + data['country_name'] + "</td>\n\
                           <td class='col data-grid-region'>" + data['region_name'] + "</td>\n\
                           <td class='col data-grid-dest-city'>"+data['dest_city']+"</td>\n\
                           <td class='col data-grid-dest-zip'>" + data['dest_zip'] + "</td>\n\
                           <td class='col data-grid-dest-zip-to'>" + data['dest_zip_to'] + "</td>\n\
                           <td class='col data-grid-condition-from'>" + data['condition_from_value'] + "</td>\n\
                           <td class='col data-grid-condition-to'>" + data['condition_to_value'] + "</td>\n\
                           <td class='col data-grid-price'>" + data['price'] + "</td>\n\
\n\                        <td class='col data-grid-shipping-method'>" + data['shipping_method'] + "</td>\n\
                           <td class='col data-grid-actions-cell'>\n\
                            <a href='javascript:void(0);' class='action view editbtn'>\n\
                            Edit\n\
                            </a>\n\
                            <a href='javascript:void(0)' data-url='" + data['delete_url'] + "' class='action delete deletebtn'>\n\
                                <span><?php echo __('Delete') ?></span>\n\
                            </a>\n\</td></tr></td>";

                        if ($("tr.row-"+data['pk']).attr("class") == undefined) {
                            html += "</tr>";
                        }
                        if (data.success) {
                            if ($("tr.row-"+data['pk']).attr('class') != undefined)
                            {
                                $("tr.row-"+data['pk']).html(html);

                            } else if ($('#matrix-rate-table > tbody > tr#message-info-shipping-rate').attr("id") == undefined ) {
                                $('#matrix-rate-table > tbody > tr:first').before(html);
                            } else {
                                $('#matrix-rate-table > tbody').html(html);
                            }
                        }
                        
                        if(data.successMessage){
                            $("#shipping_rates_modal_popup").html(data.successMessage);
                            var popup = modal(options, $('#shipping_rates_modal_popup'));
                            $("#shipping_rates_modal_popup").modal('openModal');
                        }


                        $("#success").show();
                        $("#savebtn").text('Add');
                        $('#matrix_rate_form')[0].reset();
                        $('#pk').val('');
                    },
                    error: function (data) {
                        $("#error").show();
                    }
                    });
                }
            });

            /*edit rates usgin ajax */
            $(document).on('click', '.editbtn', function () {
                var rateId = $(this).parents('tr').find('.rate-display-id').html();
                var editurl = "<?php echo $this->getUrl('rbshippingmatrix/rates/edit/'); ?>" + "id/" + rateId;
                $.ajax({
                    showLoader: true,
                    url: editurl,
                    type: "GET",
                    dataType: 'json'
                }).done(function (data) {
                    if(data.redirectUrl){
                        window.location.href = data.redirectUrl;
                    } else {                    
                        getRegion(data['dest_country_id'], data['dest_region_id']);
                        $("#pk").val(data['pk']);
                        $("select#dest_country_id").val(data['dest_country_id']);
                        $("select#dest_region_id").val(data['dest_region_id']);
                        $("#dest_city").val(data['dest_city']);
                        $("#dest_zip").val(data['dest_zip']);
                        $("#dest_zip_to").val(data['dest_zip_to']);
                        $("#condition_name").val(data['condition_name']);
                        $("#condition_from_value").val(data['condition_from_value']);
                        $("#condition_to_value").val(data['condition_to_value']);
                        $("#price").val(data['price']);
                        $("#shipping-method").val(data['shipping_method']);
                        $("#savebtn").text('Update');
                    }
                });
            });

            /*delete rates */
            $(document).on('click', '.deletebtn', function () {
                var url = $(this).attr('data-url');
                confirmation({
                    title: '',
                    content: 'Are you sure to delete this shipping rates?',
                    actions: {
                        confirm: function () {
                            window.location.href = url;
                        },
                        cancel: function () {
                        }
                    },
                    buttons: [{
                            text: $.mage.__('OK'),
                            class: 'action secondary action-accept',
                            /**
                             * Click handler.
                             */
                            click: function (event) {
                                this.closeModal(event, true);
                            }
                        },
                        {
                            text: $.mage.__('Cancel'),
                            class: 'action secondary action-dismiss',
                            /**
                             * Click handler.
                             */
                            click: function (event) {
                                this.closeModal(event);
                            }
                        }
                    ]
                });
            });

            $(document).on('click', '#cancel', function () {
                $("#savebtn").text('Add');
                $('#matrix_rate_form')[0].reset();
                $('#pk').val('');
            });

        });
        function getRegion(countryId, regionId)
        {
            var region_id = '';

            if (regionId !== '' && typeof regionId !== undefined)
            {
                region_id = '/region_id/' + regionId;
            }
            var requestUrl = "<?php echo $this->getUrl('rbshippingmatrix/rates/regionlist'); ?>" + 'country_id/' + countryId + region_id;
            $.ajax({
                showLoader: true,
                url: requestUrl,
                type: "GET",
                dataType: 'json'
            }).done(function (data) {
                $('#dest_region_id').empty();
                $('#dest_region_id').append(data.htmlconent);
            });
        }
        
        $('.rbshippingmatrix-guidelines').on('click', function(event) {
            event.preventDefault();
            var w = window.open($(this).data('href'), "popupWindow", "top=150,left=400,width=800, height=500, scrollbars=yes");
            var $w = $(w.document.body);
        });
    });
</script>