<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Catalog
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
 /** @var $block Magedelight\Catalog\Block\Product\Edit\Vitalinfo */
?>
<div id="product-vital-info-form-content" class="product-vital-info-form-content">
<?php if ($block->getAttributesHtml()) { ?>
    <fieldset class="fieldset">
    <?= $block->getAttributesHtml(); ?>
    </fieldset>
    <?php
} else { ?>
    <?= __('Sorry, No attributes found.');
}
?>
</div>