<div class="view_in_app">
	<div class="open_in_app_icon">
		<img src="<?php echo $block->getViewFileUrl('MDC_Catalog::images/tamta_app_dwload.png'); ?>" alt="">
	</div>
	<div class="open_in_app_description">
		<div class="tet"><?= __("Get tamata app on your phone now"); ?></div>
		<!-- <div class="tt"><?= __("Download the application");?></div> -->
	</div>
	<div class="open_in_app_link">
		<a class="button" href="<?php echo $block->getCurrentProduct();   ?>"> <?= __("View in app"); ?> </a>
	</div>
</div>