<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_ProductAlert
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<?php $block->setPreconfiguredValue(); ?>
<?php $_product = $block->getProduct(); ?>
<?php $_associatedProducts = $block->getAssociatedProducts(); ?>
<?php $_hasAssociatedProducts = count($_associatedProducts) > 0; ?>

<div class="table-wrapper grouped">
    <table class="table data grouped" id="super-product-table">
        <caption class="table-caption"><?php  echo __('Grouped product items') ?></caption>
        <thead>
        <tr>
            <th class="col item" scope="col"><?php  echo __('Product Name') ?></th>
            <?php if ($_product->isSaleable()) : ?>
                <th class="col qty" scope="col"><?php  echo __('Qty') ?></th>
            <?php endif; ?>
        </tr>
        </thead>

        <?php if ($_hasAssociatedProducts) : ?>
            <?php foreach ($_associatedProducts as $_item) : ?>
                <tbody>
                <tr>
                    <td data-th="<?php echo $block->escapeHtml(__('Product Name')); ?>" class="col item">
                        <strong class="product-item-name"><?php echo $block->escapeHtml($_item->getName()) ?></strong>
                        <?php if ($block->getCanShowProductPrice($_product)) : ?>
                            <?php if ($block->getCanShowProductPrice($_item)) : ?>
                                <?php  echo $block->getProductPrice($_item) ?>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php
                        /* block start*/
                        if (!$_item->isSaleable()) {
                            echo $this->helper('Magedelight\ProductAlert\Helper\Data')->getStockAlert($_item);
                        }

                        /* block end*/
                        ?>
                    </td>
                    <?php if ($_product->isSaleable()) : ?>
                        <td data-th="<?php echo $block->escapeHtml(__('Qty')); ?>" class="col qty">
                            <?php if ($_item->isSaleable()) : ?>
                                <div class="control qty">
                                    <input type="number" name="super_group[<?php  echo $_item->getId() ?>]"
                                           data-selector="super_group[<?php  echo $_item->getId() ?>]"
                                           maxlength="12"
                                           value="<?php  echo $_item->getQty() * 1 ?>"
                                           title="<?php  echo __('Qty') ?>"
                                           class="input-text qty"
                                           data-validate="{'validate-grouped-qty':'#super-product-table'}"
                                           data-errors-message-box="#validation-message-box"/>
                                </div>
                            <?php else : ?>
                                <div class="stock unavailable" title="<?php  echo __('Availability') ?>">
                                    <span><?php  echo __('Out of stock') ?></span>
                                </div>
                            <?php endif; ?>
                        </td>
                    <?php endif; ?>
                </tr>
                <?php if ($block->getCanShowProductPrice($_product)
                    && $block->getCanShowProductPrice($_item)
                    && trim($block->getProductPriceHtml(
                        $_item,
                        \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                    ))) : ?>
                    <tr class="row-tier-price">
                        <td colspan="2">
                            <?php echo $block->getProductPriceHtml(
                                $_item,
                                \Magento\Catalog\Pricing\Price\TierPrice::PRICE_CODE
                            ) ?>
                        </td>
                    </tr>
                <?php endif; ?>
                </tbody>
            <?php endforeach; ?>
        <?php else : ?>
            <tbody>
            <tr>
                <td class="unavailable"
                    colspan="<?php if ($_product->isSaleable()) : ?>4<?php else : ?>3<?php endif; ?>">
                    <?php  echo __('No options of this product are available.') ?>
                </td>
            </tr>
            </tbody>
        <?php endif; ?>
    </table>
</div>
<div id="validation-message-box"></div>
<script type="text/javascript">
    require([
        'jquery',
        'Magento_Catalog/product/view/validation',
    ], function ($, validation) {
        "use strict";
        $('.rb-block .md_guest_email').attr('data-validate', "");
        $('.rb-block .md_guest_action button').click(function(event) {
            event.preventDefault();
            var parent = $(this).parents('.rb-block').first();
            if (parent) {
                var actionUrl = parent.attr('action');
            }
            if (!actionUrl) {
                return;
            }
            var f = $("<form/>",
                { action: actionUrl }
            );
           var email = parent.find('.md_guest_email');
            email.attr('data-validate', "{required:true, 'validate-email':true}");

            parent.children().each(function (child) {
                $(this).clone().prependTo( f );
            });

            f.hide().appendTo('body');
            var validator = $(email).validation({});
            if (validator.valid()) {

                f.submit();
            }
            f.remove();

            parent.find('.md_guest_email').attr('data-validate', "");
            return false;
        });
    });
</script>
