<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Catalog
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<div class="you-will-get-container">
     <span class="comment notes"><?= __('The amount will be added in base currency ').'('.$block->getCurrencyCode().')';?> 
      
      <a class="price-update-desc-switch tooltil-help" href="javascript:void(0)"><span><?= __('more');?></span></a><span class="price-update-description" style="display: none;"><?php $block->getCurrencyDesc();//echo __("Tunitia Dollar : 5.0000 USD Euro : 0.72 USD");?></span>
     </span>
</div>


<script type="text/javascript">
require([
        'jquery', /* jquery Library */
        "mage/calendar", /* Calender widget */
        'mage/translate', /* Magento text translate (Validation message translte as per language) */
        'mage/mage',
        'mage/validation'
    ], function ($) {
        $parent = $('#product_request_info_form');
$('.price-update-desc-switch').click(function() {
     $('.price-update-description',$parent).slideToggle(400);
            });
});
</script>
 
<?php
?>