<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_PageSpeedOptimizer
 */
?>
<?php
/** @var \Amasty\PageSpeedOptimizer\Block\Adminhtml\Settings\ProductionModeInfo $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div class="amasty-page-code">
    <?= $escaper->escapeHtml(
        __(
            'Please note that Magento Production mode should be set instead of Developer or '
            . 'Default to get the best performance of the settings below.'
        )
    ); ?>
</div>
