<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Sales
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<?php /*$_source = $block->getSource(); ?>
<?php $block->setPriceDataObject($_source) ?>
<?php if ($_source): ?>
<table width="100%">
    <?php echo $block->getChildHtml('main'); ?>
    <?php echo $block->getChildHtml('footer'); ?>
</table>
<?php endif;*/ ?>
<table class="data table order-subtotal-table">
    <?php $_totals = $block->getTotals('footer')?>

    <?php if ($_totals) :?>
        <tfoot>
            <?php foreach ($block->getTotals('footer') as $_code => $_total) : ?>
                <?php if ($_total->getBlockName()) : ?>
                    <?= $block->getChildHtml($_total->getBlockName(), false); ?>
                <?php else :?>
                <tr class="col-<?= /* @escapeNotVerified */ $_code?>">
                    <td <?= /* @escapeNotVerified */ $block->getLabelProperties()?> class="label">
                        <strong><?= $block->escapeHtml($_total->getLabel()); ?></strong>
                    </td>
                    <td <?= /* @escapeNotVerified */ $block->getValueProperties()?>>
                        <strong><?= /* @escapeNotVerified */ $block->formatValue($_total) ?></strong>
                    </td>
                </tr>
                <?php endif?>
            <?php endforeach?>
        </tfoot>
    <?php endif?>

    <?php $_totals = $block->getTotals('')?>
    <?php if ($_totals) :?>
        <tbody>
            <?php foreach ($_totals as $_code => $_total) : ?>
                <?php if ($_total->getBlockName()) : ?>
                    <?= $block->getChildHtml($_total->getBlockName(), false); ?>
                <?php else :?>
                    <tr class="col-<?= /* @escapeNotVerified */ $_code?>">
                        <td <?= /* @escapeNotVerified */ $block->getLabelProperties()?> class="label">
                            <?php if ($_total->getStrong()) :?>
                            <strong><?= $block->escapeHtml($_total->getLabel()); ?></strong>
                            <?php else :?>
                                <?= $block->escapeHtml($_total->getLabel()); ?>
                            <?php endif?>
                        </td>

                        <?php if ($_total->getStrong()) :?>
                            <td <?= /* @escapeNotVerified */ $block->getValueProperties()?>>
                                <strong><?= /* @escapeNotVerified */ $block->formatValue($_total) ?></strong>
                            </td>
                        <?php else :?>
                            <td <?= /* @escapeNotVerified */ $block->getValueProperties()?>>
                                <span><?= /* @escapeNotVerified */ $block->formatValue($_total) ?></span>
                            </td>
                        <?php endif?>
                    </tr>
                <?php endif?>
            <?php endforeach?>
        </tbody>
    <?php endif?>
</table>
