<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Sales
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
    <div class="rbpanel credit-memo-wrapper mb20">
        <form id="edit_form" method="post" action="<?= /* @escapeNotVerified */ $block->getSaveUrl() ?>">
            <?= $block->getBlockHtml('formkey')?>
            <?php  $_order = $block->getCreditmemo()->getOrder() ?>

            <?= $block->getChildHtml('rbsales_order_info') ?>
        <div class="rbpanel-heading heading-l">
            <span class="title"><?= /* @escapeNotVerified */ __('Payment Information') ?></span>
        </div>

        <div class="rbpanel-body mb">
            <div class="row row-gutter order-date-status credit-memo-order-account mb5">
                <div class="col-md-3">
                    <div class="rbpanel">
                        <div class="rbpanel-heading">
                            <span class="title"><?= /* @escapeNotVerified */ __('Payment &amp; Shipping Method') ?></span>
                        </div>
                        
                        <div class="rbpanel-body minh175">
                            <div class="front__page-section-item order-payment-method <?= ($_order->getIsVirtual())?'order-payment-method-virtual':''; ?>">
                                <?php /* Billing Address */ ?>
                                <div class="front__page-section-item-title">
                                    <span class="title"><?= /* @escapeNotVerified */ __('Payment Information') ?></span>
                                </div>
                                <div class="front__page-section-item-content">
                                    <div class="order-payment-method-title"><?= $block->getChildHtml('rbsales_order_payment') ?></div>
                                    <div class="order-payment-currency">
                                        <?= /* @escapeNotVerified */ __('The order was placed using %1.', $_order->getOrderCurrencyCode()) ?>
                                    </div>
                                    <div class="order-payment-additional">
                                        <?= $block->getChildHtml('rbsales_order_payment_additional'); ?>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            
                
                <?php if (!$_order->getIsVirtual()) : ?>
                    <div class="col-md-3">
                        <div class="rbpanel">
                            <div class="rbpanel-heading">
                                <span class="title"><?= /* @escapeNotVerified */ __('Shipping Information') ?></span>
                            </div>

                            <div class="rbpanel-body minh175">
                                <div class="front__page-section-item-content shipping-description-wrapper">
                                    <div class="shipping-description-title"><?= $block->escapeHtml($_order->getShippingDescription()) ?></div>
                                    <div class="shipping-description-content">
                                        <?= /* @escapeNotVerified */ __('Total Shipping Charges'); ?>:

                                        <?php if ($this->helper('Magento\Tax\Helper\Data')->displaySalesPriceInclTax($block->getSource()->getStoreId())) : ?>
                                            <?php $_excl = $block->displayShippingPriceInclTax($_order); ?>
                                        <?php else : ?>
                                            <?php $_excl = $block->displayPriceAttribute('shipping_amount', false, ' '); ?>
                                        <?php endif; ?>
                                        <?php $_incl = $block->displayShippingPriceInclTax($_order); ?>

                                        <?= /* @escapeNotVerified */ $_excl; ?>
                                        <?php if ($this->helper('Magento\Tax\Helper\Data')->displaySalesBothPrices($block->getSource()->getStoreId()) && $_incl != $_excl) : ?>
                                            (<?= /* @escapeNotVerified */ __('Incl. Tax'); ?> <?= /* @escapeNotVerified */ $_incl; ?>)
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endif; ?>
            </div>
        </div>
    
        <div id="creditmemo_item_container">
            <?= $block->getChildHtml('rbsales_order_items') ?>
        </div>
    </form>
</div>
