<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Sales
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<?php $_items = $block->getCreditmemo()->getAllItems() ?>
<?php $vId = $block->getCreditmemo()->getVendorId(); ?>
<div class="rbpanel-heading heading-l">
    <span class="title"><?= /* @escapeNotVerified */ __('Items to Refund') ?></span>
</div>

<div class="rbpanel-body mb">
    <div class="row row-gutter order-date-status credit-memo-order-account mb5">

        <div class="col-md-12">
            <?php if (count($_items)) : ?>
            <div class="table-wrapper front__table-wrapper">
                <table class="data table data-table front__table-primary order-creditmemo-tables">
                    <thead>
                        <tr class="headings">
                            <th class="col-product"><span><?= /* @escapeNotVerified */ __('Product') ?></span></th>
                            <th class="col-price"><span><?= /* @escapeNotVerified */ __('Price') ?></span></th>
                            <th class="col-ordered-qty"><span><?= /* @escapeNotVerified */ __('Qty') ?></span></th>
                            <?php if ($block->canReturnToStock()) : ?>
                            <th class="col-return-to-stock"><span><?= /* @escapeNotVerified */ __('Return to Stock') ?></span></th>
                            <?php endif; ?>
                            <th class="col-refund"><span><?= /* @escapeNotVerified */ __('Qty to Refund') ?></span></th>
                            <th class="col-subtotal"><span><?= /* @escapeNotVerified */ __('Subtotal') ?></span></th>
                            <th class="col-tax-amount"><span><?= /* @escapeNotVerified */ __('Tax Amount') ?></span></th>
                            <th class="col-discont"><span><?= /* @escapeNotVerified */ __('Discount Amount') ?></span></th>
                            <th class="col-total last"><span><?= /* @escapeNotVerified */ __('Row Total') ?></span></th>
                        </tr>
                    </thead>
                    <?php if ($block->canEditQty()) : ?>
                    <tfoot>
                        <tr>
                            <td colspan="3">&nbsp;</td>
                            <td colspan="3">
                                <?= $block->getUpdateButtonHtml() ?>
                            </td>
                            <td colspan="3" class="last">&nbsp;</td>
                        </tr>
                    </tfoot>
                    <?php endif; ?>
                    <?php $i = 0; foreach ($_items as $_item) : ?>
                        <?php if ($_item->getOrderItem()->getVendorId() != $vId || $_item->getOrderItem()->getParentItem() || $_item->getQty() <= 0) {
                            continue;
                        } else {
                            $i++;
                        } ?>
                        <tbody class="<?= /* @escapeNotVerified */ $i%2 ? 'even' : 'odd' ?>">
                            <?= $block->getItemHtml($_item) ?>
                            <?= $block->getItemExtraInfoHtml($_item->getOrderItem()) ?>
                        </tbody>
                    <?php endforeach; ?>
                </table>
            </div>
            <?php else : ?>
            <div class="no-items">
                <?= /* @escapeNotVerified */ __('No Items To Refund') ?>
            </div>
            <?php endif; ?>
        </div>
    </div>
</div>



<?php $orderTotalBar = $block->getChildHtml('rbsales_order_totalbar'); ?>

<?php if (!empty($orderTotalBar)) : ?>
<section class="fieldset-wrapper">
    <?= /* @escapeNotVerified */ $orderTotalBar; ?>
</section>
<?php endif; ?>


<div class="rbpanel-heading heading-l">
            <span class="title"><?= /* @escapeNotVerified */ __('Order Total') ?></span>
</div>
<div class="rbpanel-body mb">
    <div class="row row-gutter order-date-status credit-memo-order-account mb5">
        <input type="hidden" name="creditmemo[do_offline]" id="creditmemo_do_offline" value="0" />
                <div class="col-md-6">
                    <div class="front__page-section-item order-comments-history">
                        <div class="front__page-section-item-title">
                            <span class="title"><?= /* @escapeNotVerified */ __('Credit Memo Comments') ?></span>
                        </div>
                        <div id="history_form" class="front__fieldset-wrapper-content">
                            <fieldset class="fieldset">
                                <div class="field comment-text">
                                    <label class="label" for="creditmemo_comment_text">
                                        <span><?= /* @escapeNotVerified */ __('Comment Text') ?></span>
                                    </label>
                                    <div class="control">
                                        <textarea id="creditmemo_comment_text"
                                              class="input-text text-area"
                                              name="creditmemo[comment_text]"
                                              rows="3"
                                              cols="5"><?= /* @escapeNotVerified */ $block->getCreditmemo()->getCommentText(); ?></textarea>
                                    </div>
                                </div>
                                
                                
                            </fieldset>
                        </div>
                    </div>
                </div>
                
                <div class="col-md-6">
                    <div class="front__page-section-item order-totals creditmemo-totals">
                        <div class="front__page-section-item-title">
                            <span class="title"><?= /* @escapeNotVerified */ __('Refund Totals') ?></span>
                        </div>
                        <?= $block->getChildHtml('rbsales_creditmemo_totals') ?>
                        <div class="order-totals-actions">
                            <div class="field choice front__field front__field-option field-append-comments mb10">
                                <input id="notify_customer"
                                       class="front__control-checkbox"
                                       name="creditmemo[comment_customer_notify]"
                                       value="1"
                                       type="checkbox" />
                                <label for="notify_customer" class="front__field-label">
                                    <span><?= /* @escapeNotVerified */ __('Append Comments') ?></span>
                                </label>
                            </div>
                            <?php if ($block->canSendCreditmemoEmail()) :?>
                            <div class="field choice front__field front__field-option field-email-copy mb10">
                                <input id="send_email"
                                       class="front__control-checkbox"
                                       name="creditmemo[send_email]"
                                       value="1"
                                       type="checkbox" />
                                <label for="send_email" class="front__field-label">
                                    <span><?= /* @escapeNotVerified */ __('Email Copy of Credit Memo') ?></span>
                                </label>
                            </div>
                            <?php endif; ?>
                            <?= $block->getChildHtml('submit_before') ?>
                            <div class="action-toolbar">
                                <?= $block->getChildHtml('submit_offline') ?>
                                <?= $block->getChildHtml('submit_button') ?>
                                <?= $block->getChildHtml('submit_after') ?>
                            </div>
                        </div>
                    </div>
                </div>
            
        
    </div>
</div>


<script>
require(['jquery', 'prototype'], function(jQuery){

//<![CDATA[
var submitButtons = $$('.submit-button');
var updateButtons = $$('.update-button,.update-totals-button');
var fields = $$('.qty-input,.order-subtotal-table input[type="text"]');

updateButtons.each(function (elem) {elem.disabled=true;elem.addClassName('disabled');});

for(var i=0;i<fields.length;i++){
    fields[i].observe('change', checkButtonsRelation)
    fields[i].baseValue = fields[i].value;
}

function checkButtonsRelation() {
    var hasChanges = false;
    fields.each(function (elem) {
        if (elem.baseValue != elem.value) {
            hasChanges = true;
        }
    }.bind(this));
    if (hasChanges) {
        submitButtons.each(function (elem) {elem.disabled=true;elem.addClassName('disabled');});
        updateButtons.each(function (elem) {elem.disabled=false;elem.removeClassName('disabled');});
    }
    else {
        submitButtons.each(function (elem) {elem.disabled=false;elem.removeClassName('disabled');});
        updateButtons.each(function (elem) {elem.disabled=true;elem.addClassName('disabled');});
    }
}

submitCreditMemo = function() {
    if ($('creditmemo_do_offline')) $('creditmemo_do_offline').value=0;
    // Temporary solution will be replaced after refactoring order functionality
    jQuery('#edit_form').triggerHandler('save');
}

submitCreditMemoOffline = function() {
    if ($('creditmemo_do_offline')) $('creditmemo_do_offline').value=1;
    // Temporary solution will be replaced after refactoring order functionality
    jQuery('#edit_form').triggerHandler('save');
}

var sendEmailCheckbox = $('send_email');

if (sendEmailCheckbox) {
    var notifyCustomerCheckbox = $('notify_customer');
    var creditmemoCommentText = $('creditmemo_comment_text');
    Event.observe(sendEmailCheckbox, 'change', bindSendEmail);
    bindSendEmail();
}

function bindSendEmail()
{
    if (sendEmailCheckbox.checked == true) {
        notifyCustomerCheckbox.disabled = false;
        //creditmemoCommentText.disabled = false;
    }
    else {
        notifyCustomerCheckbox.disabled = true;
        //creditmemoCommentText.disabled = true;
    }
}

window.bindSendEmail = bindSendEmail;
window.checkButtonsRelation = checkButtonsRelation;
//]]>

});
</script>
