<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var \Magento\Wishlist\Block\Link $block */
//$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
//$customerSession = $objectManager->get('Magento\Customer\Model\Session');
$customerSession = $this->getLayout()->createBlock('Ktpl\Wishlist\Model\WishlistManager');
// $blockObj= $block->getLayout()->createBlock('Magento\Customer\Model\Session');
// echo $blockObj->isLoggedIn();


?>
<li class="link wishlist md-custom-toplink" data-bind="scope: 'wishlist'">
    <?php if ($customerSession->checkLoggedIn()) { ?>
    <a <?= /* @noEscape */ $block->getLinkAttributes() ?> class="md-login-form">
    <?php } else { ?>
    <a href="javascript:void(0)" class="md-login-form">
    <?php } ?>
        <?= $block->escapeHtml($block->getLabel()) ?>
        <!-- ko if: wishlist().counter -->
        <span data-bind="text: wishlist().counter" class="counter qty"></span>
        <!-- /ko -->
    </a>
</li>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }

</script>
