<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Shippingmatrix
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<div class="bulkimport-guidelines">
    <div class="bulkimport-step2">
        <div class="title"><?php echo __('Shipping Method');?></div>

        <div class="field-description-wrapper">
            <div class="field-description-container">
                <h2><?php echo __('Fields Description');?></h2>
                <ul>
                    <li>
                        <strong><?php echo __('Country');?></strong>
                        <?php echo __("Enter the name of the country."); ?>
                    </li>
                    <li>
                        <strong><?php echo __('Region');?></strong>
                        <?php echo __("Enter the name of the region by default it take All Region in specific country."); ?>
                    </li>
                    <li>
                        <strong><?php echo __('City');?></strong>
                        <?php echo __("Enter the name of the city by default it take All City into specific region."); ?>
                    </li>
                    <li>
                        <strong><?php echo __('ZipCode From');?></strong>
                        <?php echo __("Enter the from ZipCode starting point."); ?>
                    </li>
                    <li>
                        <strong><?php echo __('ZipCode To');?></strong>
                        <?php echo __("Enter the from ZipCode ending point.")?>
                    </li>
                    <li>
                        <strong><?php echo __('Weight From');?></strong>
                        <?php echo __("Enter the Weight From."); ?>
                    </li>
                    <li>
                        <strong><?php echo __('Weight To');?></strong>
                        <?php echo __("Enter the Weight To."); ?>
                    </li>
                    <li>
                        <strong><?php echo __('Shipping Method');?></strong>
                        <?php echo __("Enter the shipping method id."); ?>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>