<?php

use Magento\Framework\App\Action\Action;

$AIRecommendHelper = $this->helper('CAT\AIRecommend\Helper\Data');
if ($AIRecommendHelper->isEnabled()) : 
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$vendorHelper = $this->helper('Magedelight\Vendor\Helper\Data');
?>
<?php
$viewMode = 'grid';
$image = 'category_page_grid';
$showDescription = false;
$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;

/**
 * Position for actions regarding image size changing in vde if needed
 */
$pos = $block->getPositioned();
$position = '';
$product_list_order = $this->getRequest()->getParam('product_list_order');
?>
<div class="toolbar-sorter sorter" onclick="void(0);" style="margin: 10px 5px 0px 0px">
    <label class="sorter-label"><?= __('Sort By');?></label>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <option value="ms_default" <?php if(in_array($product_list_order, ['', 'ms_default'])) {?> selected="selected" <?php } ?>><?= __('Default'); ?></option>
        <option value="ms_position" <?php if($product_list_order == 'ms_position') {?> selected="selected" <?php } ?>><?= __('Position'); ?></option>
    </select>
    <ul class="sorter-data">
        <li><a href="?product_list_order=ms_default" class="default_sort_order <?php if(in_array($product_list_order, ['', 'ms_default'])) {?> selected_sorted_option <?php } ?>"><?= __('Default'); ?></a></li>
        <li><a href="?product_list_order=ms_position" class="position_sort_order <?php if($product_list_order == 'ms_position') {?> selected_sorted_option <?php } ?>"><?= __('Position'); ?></a></li>
    </ul>
</div>
<br/>
<br/>
<div class="mc-plp-wrap">
<?php if (count($_productCollection)) : ?>
    <div class="products wrapper microsite-product-grid <?php echo $viewMode; ?> products-<?php echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol  class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product) : ?>
                <?php echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php if ($vendorHelper->isModuleEnabled('RB_QuickShop') && $vendorHelper->getConfigValue('quickshop/general/active')) :?>
                    <div class="qs-btn-container"><a class="qs-button" href="javascript:void(0)" data-href="<?php echo $this->getUrl('quickshop/index/view', ['id' => $_product->getId()]) ?>"><span><?php echo __('Quick Shop'); ?></span></a></div>
                    <?php endif;?>
                    <?php /* Product Image */ ?>
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl().'?v='.$this->getRequest()->getParam('vid') ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                    </a>
                    <div class="product details product-item-details">
                        <?php
                        $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl().'?v='.$this->getRequest()->getParam('vid') ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                        </strong>

                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>

                         <!-- /*.....Custom review section Start.....*/ -->
                            <?php
                                $productId = $_product->getId();
                                $ratingData = $this->getLayout()->createBlock('Ktpl\Productslider\Block\CategoryId')->getReviewSummary($productId);
                                $ratingSummary = $ratingData['ratingSummary'];
                                $ratingSummaryCount = ((5*$ratingSummary)/100);
                                $reviewCount = $ratingData['reviewCount'];
                                ?>
                                <?php if ($ratingSummary) { ?>
                                <div class="product-reviews-summary short">
                                    <div class="rating-summary">
                                        <div title="<?php echo (int)$ratingSummary; ?>%" class="rating-result">
                                            <span style="width:<?php echo (int)$ratingSummary; ?>%"><span><?php echo (int)$ratingSummary; ?>%</span></span>
                                        </div>
                                    </div>
                                    <div class="reviews-actions">
                                        <?php echo number_format($ratingSummaryCount, 1); ?>
                                    </div>
                                </div>
                            <?php  } else { ?>
                                <div class="short empty">
                                    <div class="reviews-actions">
                                        <a class="action add" href="<?= $_product->getProductUrl().'#review-form' ?>">
                                            <?= $block->escapeHtml(__('Leave a Review')) ?>
                                        </a>
                                    </div>
                                </div>
                            <?php } ?>
                        <!-- /*.....Custom review section End.....*/ -->

                        <!-- <div class="rating-summary">
                            <div class="rating-result">
                                <span style="width:<?php //echo $block->getRatingSummary($_product); ?>%"><span><span itemprop="ratingValue"><?php //echo $block->getRatingSummary($_product); ?></span>% of <span itemprop="bestRating">100</span></span></span>
                            </div>
                        </div> -->

                        <div class="product-item-inner">
                            <div class="product actions product-item-actions">
                                <div class="actions-primary">
                                    <?php if ($_product->isSaleable()) : ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product);
                                        ?>
                                        <?php
                                        $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getEntityId()])
                                        ?>

                                        <!--<form data-role="tocart-form" data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>" action="<?= /* @NoEscape */ $postParams['action'] ?>" method="post">
                                            <input type="hidden" name="product" value="<?= /* @escapeNotVerified */ $postParams['data']['product'] ?>">
                                            <input type="hidden" name="vendor_id" value="<?= $this->getRequest()->getParam('vid') ?>" />
                                            <input type="hidden" name="<?= /* @escapeNotVerified */ Action::PARAM_NAME_URL_ENCODED ?>" value="<?= /* @escapeNotVerified */ $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                            <?= $block->getBlockHtml('formkey') ?>
                                            <button type="submit"
                                                    title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                    class="action tocart primary">
                                                <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                            </button>
                                        </form>-->
                                    <?php else : ?>
                                        <?php if ($_product->getIsSalable()) : ?>
                                            <div class="stock available"><span><?= /* @escapeNotVerified */ __('In stock') ?></span></div>
                                        <?php else : ?>
                                            <div class="stock unavailable"><span><?= /* @escapeNotVerified */ __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div class="actions-secondary" data-role="add-to-links">
                                    <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()) : ?>
                                        <a href="#"
                                           data-post='<?= /* @escapeNotVerified */ $block->getAddToWishlistParams($_product) ?>'
                                           class="action towishlist" data-action="add-to-wishlist"
                                           title="<?= /* @escapeNotVerified */ __('Add to Wish List') ?>">
                                            <span><?= /* @escapeNotVerified */ __('Add to Wish List') ?></span>
                                        </a>
                                    <?php endif; ?>
                                    <?php if ($block->getAddToCompareUrl()) : ?>
                                        <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');?>
                                        <a href="#" class="action tocompare"
                                           data-post='<?= /* @escapeNotVerified */ $compareHelper->getPostDataParams($_product) ?>'
                                           title="<?= /* @escapeNotVerified */ __('Add to Compare') ?>">
                                            <span><?= /* @escapeNotVerified */ __('Add to Compare') ?></span>
                                        </a>
                                    <?php endif; ?>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
                <?php echo($iterator == count($_productCollection) + 1) ? '</li>' : '' ?>
            <?php endforeach; ?>
    </ol>
        <div style="clear: both"></div>
    </div>
    <?php if ($block->getToolbarHtml()) : ?>
            <?= $block->getToolbarHtml(); ?>
    <?php endif ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php else : ?>
<div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('Products not available.') ?></div></div>
<?php endif; ?>
</div>
<?php endif; ?>
