<?php


use Magento\Framework\App\Action\Action;

/** @var AbstractSlider $block */

$mode = 'grid';
$title = $block->getTitle();
$viewAllLink = $block->getviewallUrl();
$items = $block->getSliderCollection();
$thresholdQtyHelper = $this->helper('MDC\Catalog\Helper\OnlyXLeft');
$AIRecommendHelper = $this->helper('CAT\AIRecommend\Helper\Data');
$title = $AIRecommendHelper->getSeasonbasedTitle($block->getStore()->getId());
if (count($items) > 0 && $AIRecommendHelper->IsSeasonbasedEnable()) : ?>
<div class="recommended-home-box ktpl-productslider-widget widget-block-prodslider">
<div class="ktpl-prodslider">
    <div class="ktpl-product-slider-block block widget block-products-list <?= $mode; ?>">
        <h3><?= $title; ?>
        </h3>
    </div>
    <div class="block-content vkvkvkvk">
        <div class="products-<?= $mode; ?> <?= $mode; ?>">
            <?php $iterator = 1; ?>
                <div id="ktpl-list-season-AI" class="owl-carousel owl-theme">
                    <?php foreach ($items as $_item) : ?>
                        <?= ($iterator++ == 1) ? '<div class="product-item product-slider item">' : '</div><div class="product-item product-slider item">' ?>
                        <div class="slider-product-item-info">
                            <div class="prod-img-box">
                              
                                    <div class="actions-secondary" data-role="add-to-links">
                                        <?php $productId = $_item->getId(); ?>
                                            <div id="wishlist_<?php echo $productId; ?>" class="action wishlist-container" data-bind="scope:'wishlist_<?php echo $productId; ?>'">
                                                <!-- ko template: getTemplate() --><!-- /ko -->
                                            </div>
                                            <script type="text/x-magento-init">
                                                {
                                                    "#wishlist_<?php echo $productId; ?>": {
                                                        "Magento_Ui/js/core/app": {
                                                           "components": {
                                                                "wishlist_<?php echo $productId; ?>": {
                                                                    "component": "Ktpl_Wishlist/js/wishlist",
                                                                    "template" : "Ktpl_Wishlist/wishlist",
                                                                    "productId": <?= /* @escapeNotVerified */ $productId ?>,
                                                                    "loginUrl": "<?= /* @escapeNotVerified */ $this->getUrl('customer/account/login') ?>"
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            </script>

                                             
                                      </div>
                                  
                                <a href="<?= $block->getProductUrl($_item) ?>"
                                   class="product photo slider-product-item-photo">
                                    <?= $block->getImage($_item, 'category_page_list')->toHtml(); ?>
                                </a>

                            </div>
                            <div class="product details slider-product-item-details">
                                <strong class="product name product-item-name">
                                    <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?= $block->getProductUrl($_item) ?>">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>
                                    <?= $block->getProductPrice($_item); ?>
                                <?php if (false) : ?>
                                    <?php
                                        if($_item->getTypeId() == \Magento\ConfigurableProduct\Model\Product\Type\Configurable::TYPE_CODE){

                                         $swatchBlock = $this->getLayout()->createBlock("Magento\Swatches\Block\Product\Renderer\Listing\Configurable")->setTemplate("Magento_Swatches::product/listing/renderer.phtml");
                                           echo $swatchBlock->setProduct($_item)->toHtml();
                                        }
                                    ?>
                                <?php endif; ?>
                                <?php
                                $productId = $_item->getId();
                                $ratingData = $block->getReviewSummary($productId);
                                $ratingSummary = $ratingData['ratingSummary'];
                                $ratingSummaryCount = ((5*$ratingSummary)/100);
                                $reviewCount = $ratingData['reviewCount'];
                                ?>

                                <?php 
                                    if($_item->getTypeId() === "simple"){
                                        $thresoldStatus = $thresholdQtyHelper->getProductXleftById($productId);

                                        if($thresoldStatus["status"] && $thresoldStatus["qty"] > 0){ ?>

                                            <div class="listing-view-only-few-lefts">
                                                <div class="availability only" title="Only <?php echo $thresoldStatus['qty'];?> left">
                                                    <?= __('Only %1 left!',"<strong>".$thresoldStatus["qty"]."</strong>") ?>
                                                </div>
                                            </div>

                                        <?php }else{
                                            ?>
                                                <div class="listing-view-only-few-lefts">
                                                    <div class="availability only empty"> 
                                                    </div>
                                                </div>
                                            <?php
                                        }
                                    }else{
                                        ?>
                                        <div class="listing-view-only-few-lefts">
                                            <div class="availability only empty"> 
                                            </div>
                                        </div>
                                        <?php
                                    }
                                ?>
                                <?php if ($ratingSummary) { ?>
                                    <div class="product-reviews-summary short">
                                        <div class="rating-summary">
                                            <div title="<?php echo (int)$ratingSummary; ?>%" class="rating-result">
                                                <span style="width:<?php echo (int)$ratingSummary; ?>%"><span><?php echo (int)$ratingSummary; ?>%</span></span>
                                            </div>
                                        </div>
                                        <div class="reviews-actions">
                                            <?php echo '('.number_format($ratingSummaryCount, 1).')'; ?>
                                        </div>
                                    </div>
                                <?php  } else { ?>
                                    <div class="short empty">
                                        <div class="reviews-actions">
                                            <a class="action add" href="<?= $_item->getProductUrl().'#review-form' ?>">
                                                <?= $block->escapeHtml(__('Write a Review')) ?>
                                            </a>
                                        </div>
                                    </div>
                                <?php } ?>
                                <?php //$block->getReviewsSummaryHtml($_item, 'short', true) ?>
                            </div>
                        </div>
                        <?= ($iterator === count($items) + 1) ? '</div>' : '' ?>
                    <?php endforeach ?>
            </div>
        </div>
        <?= $block->getPagerHtml() ?>
    </div>
</div>
    <script>
        require(['jquery', 'ktpl/productslider/owl.carousel'], function ($) {
            /*$( window ).resize(function() {*/
                if ($(window).width() >= 1024) {
                    $('#ktpl-list-season-AI').owlCarousel({responsive:{1400:{items:6},1000:{items:4},767:{items:3,autoWidth:true},220:{items:3,autoWidth:true}},loop:false,nav:true,navText: [
                                "<span class='left-arrow'>",
                                "<span class='right-arrow'>"
                            ],dots:false,lazyLoad:false,autoplay:false,autoplayHoverPause:false, <?php if($block->getStore()->getId() == 2){ echo 'rtl:true'; } ?>});
                }
            /*});*/
        });
    </script>
</div>
<?php endif; ?>
