<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\GiftCardAccount\Block\Account\Redeem $block
 * @see \Magento\GiftCardAccount\Block\Account\Redeem
 */
?>
<div class="giftcard-account">
    <span id="gc-please-wait" class="please-wait load indicator"
          data-text="<?= $block->escapeHtmlAttr(__('This won\'t take long . . .')) ?>" style="display: none;">
        <span><?= $block->escapeHtml(__('This won\'t take long . . .')) ?></span>
    </span>
    <form class="form form-giftcard-redeem" id="giftcard-form"
          action="<?= $block->escapeUrl($block->getUrl('giftcardc/redeem/index')) ?>" method="post">
        <div id="giftcard-balance-lookup" class="giftcard ballance"></div>
        <fieldset class="fieldset">
            <div class="field giftcard required">
                <label class="label" for="giftcard-code">
                    <span><?= $block->escapeHtml(__('Enter gift card code')) ?></span>
                </label>
                <div class="control">
                    <input class="input-text giftcard-code-field" id="giftcard-code" type="text" name="giftcard_code"
                           data-validate="{required:true}"
                           value="<?= /* @noEscape */
                           $block->getCurrentGiftcard() ?>" required/>
                </div>
            </div>
        </fieldset>
        <?= /* @noEscape */
        $block->getChildHtml('captcha') ?>
        <div class="actions-toolbar">
                <div class="primary">
                    <button class="action redeem primary" type="button"
                            value="<?= $block->escapeHtmlAttr(__('Redeem Gift Card')) ?>" id="redeem-submit-btn">
                        <span><?= $block->escapeHtml(__('Redeem Gift Card')) ?></span>
                    </button>
                </div>
        </div>
    </form>
</div>
<script>
    require([
        'jquery'
    ], function (jQuery) {
        jQuery("#redeem-submit-btn").click(function () {
            jQuery("#giftcard-form").submit();
            jQuery(this).attr('disabled', 'disabled');
            var fieldObj = jQuery('.giftcard-code-field');
            fieldObj.val('').prop("readonly", true);
        });
        jQuery('.giftcard-code-field').keypress(function (e) {
            if (e.which === 13) {
                jQuery(this).blur().prop("readonly", true);
                jQuery('#redeem-submit-btn').focus().attr('disabled', 'disabled');
            }
        });
    });
</script>
