<?php
/**
 * @category   CAT
 * @package    CAT_OfferPage
 * @author     mohd.salman0306@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace CAT\OfferPage\Model\ResourceModel\OfferPage;
 
class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName = 'offerpage_id';
    /**
     * Define model & resource model
     */
    protected function _construct()
    {
        $this->_init(
            'CAT\OfferPage\Model\OfferPage',
            'CAT\OfferPage\Model\ResourceModel\OfferPage'
        );
    }
}