<div class="import-export-tax-rates">
    <?php if (!$block->getIsReadonly()) : ?>
        <div class="import-tax-rates">
            <?php if ($block->getUseContainer()) : ?>
            <form id="import-form" class="admin__fieldset" action="<?= /* @escapeNotVerified */ $block->getUrl('tookan/index/importPost') ?>" method="post" enctype="multipart/form-data">
                <?php endif; ?>
                <?= $block->getBlockHtml('formkey') ?>
                <div class="fieldset admin__field">
                    <label for="import_tookan_file" class="admin__field-label"><span><?= /* @escapeNotVerified */ __('Import Tookan CSV') ?></span></label>
                    <div class="admin__field-control">
                        <input type="file" id="import_tookan_file" name="import_tookan_file" class="input-file required-entry"/>
                        <?= $block->getButtonHtml(__('Import'), '', 'import-submit') ?>
                    </div>
                </div>
                <?php if ($block->getUseContainer()) : ?>
            </form>
        <?php endif; ?>
            <script>
                require(['jquery', "mage/mage", "loadingPopup"], function(jQuery){

                    jQuery('#import-form').mage('form').mage('validation');
                    (function ($) {
                        $('.import-submit').click(function(){
                            if($(':input[name="import_tookan_file"]').val()) {
                                $('body').loadingPopup({
                                    timeout: false
                                });

                                $(this.form).submit();
                            }
                        });
                    })(jQuery);

                });
            </script>
        </div>
    <?php endif; ?>
</div>
