<div class="field" data-bind="visible: visible, attr: {'name': element.dataScope}, css: additionalClasses" name="">

    <label class="label" data-bind="attr: { for: element.uid }" for="location">
        <span data-bind="i18n: element.label"><?php echo __("Location"); ?></span>
    </label>

    <div class="control">
        <input class="input-text location required-entry" type="text" name="location_shipping" id="location">
        <div  id="custom_validation_msg"></div>
    </div>
</div>
<div id="note" class="message info" style="display:none" >
    <p>
        <?= $block->escapeHtml(__('Please drag your pin to the exact location')) ?>
    </p>
</div>
<div class="field">
    <div id="google_map" />
</div>
<style>
    #google_map {
        width: 100%;
        height: 400px;
        background-color: grey;
    }
    #location._error{border-color: #ed8380;}
</style>