<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Theme
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */

?>
<?php
/**
 * Pager template
 *
 * @see \Magento\Theme\Block\Html\Pager
 */
?>
<?php if ($block->getCollection()->getSize()): ?>
    <?php
    $limitSfrm = '';
    $pagersfrm = $block->getData('pagersfrm');
    $sfrm = $block->getRequest()->getParam('sfrm');
    if ($pagersfrm != null && $pagersfrm != '') {
        $limitSfrm = ($sfrm != $pagersfrm) ? '&sfrm='.$pagersfrm : '';
        $vpro = $block->getRequest()->getParam('vpro', false);
        $limitSfrm .= ($pagersfrm == 'nl' && !$vpro) ? '&vpro=approve' : '';
    }
    ?>

    <?php if ($block->getUseContainer()): ?>
    <div class="pager">
    <?php endif ?>

        <?php if ($block->getShowAmounts()): ?>
        <p class="toolbar-amount">
            <span class="toolbar-number">
            <?php if ($block->getLastPageNum()>1): ?>
                <?=  /* @noEscape */ __(
                    'Items %1 to %2 of %3 total',
                    $block->getFirstNum(),
                    $block->getLastNum(),
                    $block->getTotalNum()
                ) ?>
            <?php elseif ($block->getTotalNum() == 1): ?>
                <?=  /* @noEscape */ __('%1 Item', $block->getTotalNum()) ?>
            <?php else: ?>
                <?=  /* @noEscape */ __('%1 Item(s)', $block->getTotalNum()) ?>
            <?php endif; ?>
            </span>
        </p>
        <?php endif ?>

        <?php if ($block->getLastPageNum()>1): ?>
        <div class="pages">
            <strong class="label pages-label" id="paging-label"><?=  /* @noEscape */ __('Page') ?></strong>
            <ul class="items pages-items" aria-labelledby="paging-label">
            <?php if (!$block->isFirstPage() && $sfrm && $sfrm == $pagersfrm): ?>
                <li class="item pages-item-previous">
                    <?php $text = $block->getAnchorTextForPrevious() ? $block->getAnchorTextForPrevious() : '';?>
                    <a class="<?=  /* @noEscape */ $text ? 'link ' : 'action '?> previous" href="<?=  /* @noEscape */ $block->getPreviousPageUrl() ?>" title="<?=  /* @noEscape */ $text ? $text : __('Previous') ?>">
                        <span class="label"><?=  /* @noEscape */ __('Page') ?></span>
                        <span><?=  /* @noEscape */ $text ? $text : __('Previous') ?></span>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowFirst()): ?>
                <li class="item">
                    <a class="page first" href="<?=  /* @noEscape */ $block->getFirstPageUrl() ?>">
                        <span class="label"><?=  /* @noEscape */ __('Page') ?></span>
                        <span>1</span>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowPreviousJump()): ?>
                <?php
                    $previosJump = $block->getPreviousJumpPage();
                if ($sfrm && $sfrm != $pagersfrm) {
                    $tab = $this->getRequest()->getParam('tab');
                    $currentUrl = explode('tab', $block->getPageUrl($previosJump));
                    $currentPageUrl = $currentUrl[0].'tab/'.$tab;
                    $limitSfrm = '/sfrm/'.$pagersfrm.'?is_scroll=1&p='.$previosJump;
                    $previosJumpPagerUrl = str_replace('/sfrm/'.$sfrm, '', $currentPageUrl);
                    $previosJumpPagerUrl = str_replace('&amp;sfrm='.$sfrm, '', $previosJumpPagerUrl);
                    $previosJumpPagerUrl = str_replace('sfrm='.$sfrm.'&amp;', '', $previosJumpPagerUrl);
                    $previosJumpPagerUrl = $previosJumpPagerUrl.$limitSfrm;
                } else {
                    $previosJumpPagerUrl = $block->getPageUrl($previosJump);
                    $previosJumpPagerUrl = $previosJumpPagerUrl.$limitSfrm;
                }
                ?>
                <li class="item">
                    <a class="page previous jump" title="" href="<?=  /* @noEscape */ $previosJumpPagerUrl; ?>">
                        <span>...</span>
                    </a>
                </li>
            <?php endif;?>

            <?php foreach ($block->getFramePages() as $_page): ?>
                <?php if ($block->isPageCurrent($_page) && $sfrm == $pagersfrm): ?>
                    <li class="item current">
                        <strong class="page">
                            <span class="label"><?=  /* @noEscape */ __('You\'re currently reading page') ?></span>
                            <span><?=  /* @noEscape */ $_page ?></span>
                        </strong>
                    </li>
                <?php else: ?>
                    <?php
                    if ($sfrm && $sfrm != $pagersfrm) {
                        $tab = $this->getRequest()->getParam('tab');
                        $currentUrl = explode('tab', $block->getPageUrl($_page));
                        $currentPageUrl = $currentUrl[0].'tab/'.$tab;
                        $limitSfrm = '/sfrm/'.$pagersfrm.'?is_scroll=1&p='.$_page;
                        $pagerUrl = str_replace('/sfrm/'.$sfrm, '', $currentPageUrl);
                        $pagerUrl = str_replace('&amp;sfrm='.$sfrm, '', $pagerUrl);
                        $pagerUrl = str_replace('sfrm='.$sfrm.'&amp;', '', $pagerUrl);
                    } else {
                        $pagerUrl = $block->getPageUrl($_page);
                    }
                    ?>
                    <li class="item">
                        <a href="<?=  /* @noEscape */ $pagerUrl.$limitSfrm; ?>" class="page">
                            <span class="label"><?=  /* @noEscape */ __('Page') ?></span>
                            <span><?=  /* @noEscape */ $_page ?></span>
                        </a>
                    </li>
                <?php endif;?>
            <?php endforeach;?>

            <?php if ($block->canShowNextJump()): ?>
                <?php
                    $nextJump = $block->getNextJumpPage();
                if ($sfrm && $sfrm != $pagersfrm) {
                    $tab = $this->getRequest()->getParam('tab');
                    $currentUrl = explode('tab', $block->getPageUrl($nextJump));
                    $currentPageUrl = $currentUrl[0].'tab/'.$tab;
                    $limitSfrm = '/sfrm/'.$pagersfrm.'?is_scroll=1&p='.$nextJump;
                    $nextJumpPagerUrl = str_replace('/sfrm/'.$sfrm, '', $currentPageUrl);
                    $nextJumpPagerUrl = str_replace('&amp;sfrm='.$sfrm, '', $nextJumpPagerUrl);
                    $nextJumpPagerUrl = str_replace('sfrm='.$sfrm.'&amp;', '', $nextJumpPagerUrl);
                    $nextJumpPagerUrl = $nextJumpPagerUrl.$limitSfrm;
                } else {
                    $nextJumpPagerUrl = $block->getPageUrl($nextJump);
                    $nextJumpPagerUrl = $nextJumpPagerUrl.$limitSfrm;
                }
                ?>
                <li class="item">
                    <a class="page next jump" title="" href="<?=  /* @noEscape */ $nextJumpPagerUrl; ?>">
                        <span>...</span>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowLast()): ?>
                <?php
                    $showLast = $block->getLastPageUrl();
                if ($sfrm && $sfrm != $pagersfrm) {
                    $tab = $this->getRequest()->getParam('tab');
                    $currentUrl = explode('tab', $block->getPageUrl($showLast));
                    $currentPageUrl = $currentUrl[0].'tab/'.$tab;
                    $limitSfrm = '/sfrm/'.$pagersfrm.'?is_scroll=1&p='.$showLast;
                    $showLastPagerUrl = str_replace('/sfrm/'.$sfrm, '', $currentPageUrl);
                    $showLastPagerUrl = str_replace('&amp;sfrm='.$sfrm, '', $showLastPagerUrl);
                    $showLastPagerUrl = str_replace('sfrm='.$sfrm.'&amp;', '', $showLastPagerUrl);
                    $showLastPagerUrl = $showLastPagerUrl.$limitSfrm;
                } else {
                    $showLastPagerUrl = $block->getPageUrl($showLast);
                    $showLastPagerUrl = $showLastPagerUrl.$limitSfrm;
                }
                ?>
              <li class="item">
                  <a class="page last" href="<?=  /* @noEscape */ $showLastPagerUrl; ?>">
                      <span class="label"><?=  /* @noEscape */ __('Page') ?></span>
                      <span><?=  /* @noEscape */ $block->getLastPageNum() ?></span>
                  </a>
              </li>
            <?php endif;?>

            <?php if (!$block->isLastPage() && $sfrm && $sfrm != $pagersfrm): ?>
                <?php $_nextPage = $block->getCollection()->getCurPage(+1);
                if ($sfrm && $sfrm != $pagersfrm) {
                    $tab = $this->getRequest()->getParam('tab');
                    $currentUrl = explode('tab', $block->getPageUrl($_nextPage));
                    $currentPageUrl = $currentUrl[0].'tab/'.$tab;
                    $limitSfrm = '/sfrm/'.$pagersfrm.'?is_scroll=1&p='.$_nextPage;
                    $nextPagerUrl = str_replace('/sfrm/'.$sfrm, '', $currentPageUrl);
                    $nextPagerUrl = str_replace('&amp;sfrm='.$sfrm, '', $nextPagerUrl);
                    $nextPagerUrl = str_replace('sfrm='.$sfrm.'&amp;', '', $nextPagerUrl);
                    $nextPagerUrl = $nextPagerUrl.$limitSfrm;
                } else {
                    $nextPagerUrl = $block->getPageUrl($_nextPage);
                    $nextPagerUrl = $nextPagerUrl.$limitSfrm;
                }
                ?>
                <li class="item pages-item-next">
                    <?php $text = $block->getAnchorTextForNext() ? $block->getAnchorTextForNext() : '';?>
                    <a class="<?=  /* @noEscape */ $text ? 'link ' : 'action '?> next"
                       href="<?=  /* @noEscape */ $nextPagerUrl; ?>"
                       title="<?=  /* @noEscape */ $text ? $text : __('Next') ?>">
                        <span class="label"><?=  /* @noEscape */ __('Page') ?></span>
                        <span><?=  /* @noEscape */ $text ? $text : __('Next') ?></span>
                    </a>
                </li>
            <?php else:?>
                <?php $_nextPage = $block->getCollection()->getCurPage(+1);
                if ($sfrm && $sfrm != $pagersfrm) {
                    $tab = $this->getRequest()->getParam('tab');
                    $currentUrl = explode('tab', $block->getPageUrl($_nextPage));
                    $currentPageUrl = $currentUrl[0].'tab/'.$tab;
                    $limitSfrm = '/sfrm/'.$pagersfrm.'?is_scroll=1&p='.$_nextPage;
                    $nextPagerUrl = str_replace('/sfrm/'.$sfrm, '', $currentPageUrl);
                    $nextPagerUrl = str_replace('&amp;sfrm='.$sfrm, '', $nextPagerUrl);
                    $nextPagerUrl = str_replace('sfrm='.$sfrm.'&amp;', '', $nextPagerUrl);
                    $nextPagerUrl = $nextPagerUrl.$limitSfrm;
                } else {
                    $nextPagerUrl = $block->getPageUrl($_nextPage);
                    $nextPagerUrl = $nextPagerUrl.$limitSfrm;
                }
                ?>
                <li class="item pages-item-next">
                    <?php $text = $block->getAnchorTextForNext() ? $block->getAnchorTextForNext() : '';?>
                    <a class="<?=  /* @noEscape */ $text ? 'link ' : 'action '?> next"
                       href="<?=  /* @noEscape */ $nextPagerUrl; ?>"
                       title="<?=  /* @noEscape */ $text ? $text : __('Next') ?>">
                        <span class="label"><?=  /* @noEscape */ __('Page') ?></span>
                        <span><?=  /* @noEscape */ $text ? $text : __('Next') ?></span>
                    </a>
                </li>
            <?php endif;?>
            </ul>
        </div>
        <?php endif; ?>

    <?php if ($block->isShowPerPage()): ?>
        <div class="limiter">
            <strong class="limiter-label"><?=  /* @noEscape */ __('Show') ?></strong>
            <select data-mage-init='{"redirectUrl": {"event":"change"}}' class="limiter-options">
                <?php foreach ($block->getAvailableLimit() as $_key => $_limit): ?>
                    <?php
                    if ($sfrm && $sfrm != $pagersfrm) {
                        $limiterUrl = str_replace('/sfrm/'.$sfrm, '', $block->getLimitUrl($_key));
                        $limiterUrl = str_replace('&amp;sfrm='.$sfrm, '', $limiterUrl);
                        $limiterUrl = str_replace('sfrm='.$sfrm.'&amp;', '', $limiterUrl);
                    } else {
                        $limiterUrl = $block->getLimitUrl($_key);
                    }
                    ?>
                    <option value="<?=  /* @noEscape */ $limiterUrl.$limitSfrm; ?>"
                            <?= ($block->isLimitCurrent($_key))?"selected='selected'":'' ?> >
                        <?=  /* @noEscape */ $_limit ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <span class="limiter-text"><?=  /* @noEscape */ __('per page') ?></span>
        </div>
    <?php endif ?>

    <?php if ($block->getUseContainer()): ?>
    </div>
    <?php endif ?>

<?php endif ?>
