<?php
/**
 * KrishTechnolabs
 *
 * PHP version 7
 *
 * @category  KrishTechnolabs
 * @package   Ktpl_PromoCallouts
 * @copyright 2019 (c) KrishTechnolabs (https://www.KrishTechnolabs.com/)
 * @license   https://www.krishtechnolabs.com/LICENSE.txt Krish License
 * @link      https://www.krishtechnolabs.com/
 */

$sellers = $block->getBestSellersCollection();
$currentLocal = $block->getCurrentLocale();
?>
<?php if ($sellers && $sellers->getSize()) : ?>
    <div class="block-best-sellers">
        <div class="block-title">
            <h3>
                <?=  $block->escapeHtml(__('Top Partners')); ?>
            </h3>
       </div>
        <div class="block-content">
            <div class="carousel-container">
                <div id="top_partners" class="top-partners owl-carousel owl-theme">
                    <?php $iterator = 1; ?>
                    <?php foreach ($sellers as $seller) : ?>
                        <div class="item">
                            <div class="seller-image">
                                <?php if ($block->getMicrositeUrl($seller)) { ?>
                                <a title="<?= $block->escapeHtml($seller->getBusinessName()) ?>" href="<?=  $block->escapeHtml($block->getMicrositeUrl($seller)) ?>">
                                    <img src="<?= $block->escapeHtml($block->getSellerLogo($seller)); ?>" alt="<?= $block->escapeHtml($seller->getBusinessName()) ?>"/>
                                </a>
                                <?php } else { ?>
                                   <img src="<?= $block->escapeHtml($block->getSellerLogo($seller)); ?>" alt="<?= $block->escapeHtml($seller->getBusinessName()) ?>"/>
                                <?php } ?>
                            </div>
                            <div class="seller-name">
                                <?php if ($block->getMicrositeUrl($seller)) { ?>
                                <a title="<?= $block->escapeHtml($seller->getBusinessName()) ?>"
                                   href="<?=  $block->escapeHtml($block->getMicrositeUrl($seller)) ?>"
                                   class="product-item-link">
                                    <?= $block->escapeHtml($seller->getBusinessName()) ?>
                                </a>
                                <?php } else { ?>
                                    <?= $block->escapeHtml($seller->getBusinessName()) ?>
                                <?php } ?>
                            </div>
                        </div>
                    <?php endforeach; ?>
                </div>
            </div>
        </div>
    </div>
<?php if ($currentLocal == "ar") { ?>
<script type="text/javascript">
         require(["jquery","owlcarousel"],function($) {
           $(document).ready(function () {
                $("#top_partners").owlCarousel({
                autoPlay: 3000, //3000 Set AutoPlay to 3 seconds
                margin:32,
                items : 7,
                navigation : false,
                nav: true,
                loop:false,
                rtl:true,
                responsive:{
                    0:{
                        items:2,
                        margin:10,
                        autoWidth:true
                    },
                    767:{
                        items:3,
                        margin:10,
                        autoWidth:true
                    },
                    1000:{
                        items:6,
                        margin:10
                    },
                    1200:{
                        items:7,
                        margin:10
                    }
                }
          });
    });
});
</script>
<?php } else  { ?>
<script type="text/javascript">
     require(["jquery","owlcarousel"],function($) {
       $(document).ready(function () {
            $("#top_partners").owlCarousel({
            autoPlay: 3000, //3000 Set AutoPlay to 3 seconds
            margin:32,
            items : 7,
            navigation : false,
            nav: true,
            loop:false,
            responsive:{
                0:{
                    items:2,
                    margin:10,
                    autoWidth:true
                },
                767:{
                    items:3,
                    margin:10,
                    autoWidth:true
                },
                1000:{
                    items:6,
                    margin:10
                },
                1200:{
                    items:7,
                    margin:10
                }
            }
      });
});
});
</script>
<?php } ?>
<?php endif;?>