<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_Backend
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */

?>
<?php
/** @var $element \Magento\Framework\Data\Form\Element\Fieldset */
$element = $block->getElement();
$containerId = $element->getFieldsetContainerId();
$id = $element->getHtmlId();
$isCollapsable = $element->getCollapsable();
$isWrapped = $containerId || $element->getHeaderBar() || $isCollapsable;
$titleActions = '<div class="actions">' . $element->getHeaderBar() . '</div>';
$isField = $element->getFieldsetType() == 'field';
$advancedAfter = $element->getAdvancedPosition() == 'after'; // To place advanced options inside or after fieldset
$advancedLabel = $element->getAdvancedLabel();
if (!isset($advancedLabel)) {
    $advancedLabel = __('Additional Settings');
}

$cssClass = ($isField) ? 'field ' . $element->getClass() : 'fieldset rb-frontend__fieldset ' . $element->getClass();

if ($isField) {
    $count = $element->getCountBasicChildren();
    $cssClass .= ($element->hasAdvanced()) ? ' complex' : '';
}
?>

<?php
/**
 * @todo investigate situations, when the following is needed:
 * echo $element->getHeaderBar();
 * echo $element->getSubFieldsetHtml();
 */ ?>

<?php if ($isWrapped) : ?>
    <div class="fieldset-wrapper <?= ($isCollapsable) ? 'rb-frontend__collapsible-block-wrapper ' : ''; ?>"
        id="<?= /* @escapeNotVerified */ $containerId ? $containerId : $id . '-wrapper';?>"
        data-role="<?= /* @escapeNotVerified */ $id ?>-wrapper">
        <div class="fieldset-wrapper-title rb-frontend__fieldset-wrapper-title">
            <strong <?= /* @escapeNotVerified */ ($isCollapsable) ?
                'class="rb-frontend__collapsible-title" data-toggle="collapse" data-target="#' . $id . '-content"' :
                'class="title"'; ?>>
                <span><?= /* @escapeNotVerified */ $element->getLegend() ?></span>
            </strong>
            <?= /* @escapeNotVerified */ $titleActions; ?>
        </div>
        <div class="fieldset-wrapper-content rb-frontend__fieldset-wrapper-content<?= ($isCollapsable) ? ' collapse' : ''; ?>"
            id="<?= /* @escapeNotVerified */ $id ?>-content"
            data-role="<?= /* @escapeNotVerified */ $id ?>-content">
<?php endif; ?>

    <?php if (!$element->getNoContainer()) : ?>
        <fieldset class="<?= /* @escapeNotVerified */ $cssClass ?>" id="<?= /* @escapeNotVerified */ $id ?>">
        <?php if ($element->getLegend() && !$isWrapped) : ?>
            <legend class="<?= /* @escapeNotVerified */ $isField ? 'label rb-frontend__field-label' : 'rb-frontend__legend legend'?>">
                <span><?= /* @escapeNotVerified */ $element->getLegend() ?></span>
            </legend><br />
        <?php endif; ?>
    <?php endif; ?>


    <div class="messages">
        <?php if ($element->getComment() && !$isField) : ?>
            <div class="message message-notice"><?= $block->escapeHtml($element->getComment()) ?></div>
        <?php endif; ?>
    </div>


    <?=($isField) ? '<div class="control rb-frontend__field-control">' : ''; ?>

    <?php if ($element->hasHtmlContent() && !$isField) : ?>
        <?= $element->getHtmlContent(); ?>
    <?php else : ?>
        <?php if ($isField && $count > 1) :?>
            <div class="fields-group-<?= /* @escapeNotVerified */ $count?>">
        <?php endif; ?>

        <?= $element->getBasicChildrenHtml(); ?>

        <?= ($isField && $count > 1) ? '</div>' : '' ?>

        <?php if ($element->getComment() && $isField) : ?>
            <div class="note"><?= $block->escapeHtml($element->getComment()) ?></div>
        <?php endif; ?>

        <?php if ($element->hasAdvanced() && !$isField) : ?>
            <?= (!$element->getNoContainer() && $advancedAfter)  ? '</fieldset>' : ''?>
            <details data-mage-init='{"details": {}}' class="details rb-frontend__collapsible-block-wrapper" id="details<?= /* @escapeNotVerified */ $id ?>">
                <summary class="details-summary rb-frontend__collapsible-title" id="details-summary<?= /* @escapeNotVerified */ $id ?>">
                    <span><?= /* @escapeNotVerified */ $advancedLabel ?></span>
                </summary>
                <div class="details-content rb-frontend__fieldset" id="details-content<?= /* @escapeNotVerified */ $id ?>">
                    <?= $element->getAdvancedChildrenHtml(); ?>
                </div>
            </details>
        <?php elseif ($element->hasAdvanced() && $isField) : ?>
            <div class="nested" id="nested<?= /* @escapeNotVerified */ $id ?>">
                <?= $element->getAdvancedChildrenHtml(); ?>
            </div>
        <?php endif; ?>

        <?= ($isField) ? '</div>' : ''; ?>

    <?php endif; ?>


    <?php if (!$element->getNoContainer() && !$advancedAfter) : ?>
        </fieldset>
    <?php endif; ?>

<?php if ($isWrapped) : ?>
        </div>
    </div>
<?php endif; ?>
