<?php
/**
 * Magedelight
 * Copyright (C) 2019 Magedelight <info@magedelight.com>
 *
 * @category Magedelight
 * @package Magedelight_VendorPromotion
 * @copyright Copyright (c) 2019 Mage Delight (http://www.magedelight.com/)
 * @license http://opensource.org/licenses/gpl-3.0.html GNU General Public License,version 3 (GPL-3.0)
 * @author Magedelight <info@magedelight.com>
 */
?>
<?php if ($block->getCollection()->getSize()) : ?>
<?php
$limitSfrm = '';
$pagersfrm = $block->getData('pagersfrm');
$sfrm = $block->getRequest()->getParam('sfrm');
if ($pagersfrm != null && $pagersfrm != '') {
    $limitSfrm = ($sfrm != $pagersfrm) ? '&sfrm='.$pagersfrm : '';
    $vpro = $block->getRequest()->getParam('vpro', false);
    $limitSfrm .= ($pagersfrm == 'nl' && !$vpro) ? '&vpro=approve' : '';
}
?>

    <?php if ($block->getUseContainer()) : ?>
    <div class="pager">
    <?php endif ?>

        <?php if ($block->getShowAmounts()) : ?>
        <p class="toolbar-amount">
            <span class="toolbar-number">
            <?php if ($block->getLastPageNum()>1) : ?>
                <?php  echo __('Rules %1 to %2 of %3 total', $block->getFirstNum(), $block->getLastNum(), $block->getTotalNum()) ?>
            <?php elseif ($block->getTotalNum() == 1) : ?>
                <?php  echo __('%1 Rule', $block->getTotalNum()) ?>
            <?php else : ?>
                <?php  echo __('%1 Rule(s)', $block->getTotalNum()) ?>
            <?php endif; ?>
            </span>
        </p>
        <?php endif ?>

        <?php if ($block->getLastPageNum()>1) : ?>
        <div class="pages">
            <strong class="label pages-label" id="paging-label"><?php  echo __('Page') ?></strong>
            <ul class="items pages-items" aria-labelledby="paging-label">
            <?php if (!$block->isFirstPage()) : ?>
                <li class="item pages-item-previous">
                    <?php $text = $block->getAnchorTextForPrevious() ? $block->getAnchorTextForPrevious() : '';?>
                    <a class="<?php  echo $text ? 'link ' : 'action '?> previous" href="<?php  echo $block->getPreviousPageUrl() ?>" title="<?php  echo $text ? $text : __('Previous') ?>">
                        <span class="label"><?php  echo __('Page') ?></span>
                        <span><?php  echo $text ? $text : __('Previous') ?></span>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowFirst()) : ?>
                <li class="item">
                    <a class="page first" href="<?php  echo $block->getFirstPageUrl() ?>">
                        <span class="label"><?php  echo __('Page') ?></span>
                        <span>1</span>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowPreviousJump()) : ?>
                <li class="item">
                    <a class="page previous jump" title="" href="<?php  echo $block->getPreviousJumpUrl() ?>">
                        <span>...</span>
                    </a>
                </li>
            <?php endif;?>

            <?php foreach ($block->getFramePages() as $_page) : ?>
                <?php if ($block->isPageCurrent($_page)) : ?>
                    <li class="item current">
                        <strong class="page">
                            <span class="label"><?php  echo __('You\'re currently reading page') ?></span>
                            <span><?php  echo $_page ?></span>
                        </strong>
                    </li>
                <?php else : ?>
                    <?php
                    if ($sfrm && $sfrm != $pagersfrm) {
                        $pagerUrl = str_replace('/sfrm/'.$sfrm, '', $block->getPageUrl($_page));
                        $pagerUrl = str_replace('&amp;sfrm='.$sfrm, '', $pagerUrl);
                        $pagerUrl = str_replace('sfrm='.$sfrm.'&amp;', '', $pagerUrl);
                    } else {
                        $pagerUrl = $block->getPageUrl($_page);
                    }
                    ?>
                    <li class="item">
                        <a href="<?php  echo $pagerUrl.$limitSfrm; ?>" class="page">
                            <span class="label"><?php  echo __('Page') ?></span>
                            <span><?php  echo $_page ?></span>
                        </a>
                    </li>
                <?php endif;?>
            <?php endforeach;?>

            <?php if ($block->canShowNextJump()) : ?>
                <li class="item">
                    <a class="page next jump" title="" href="<?php  echo $block->getNextJumpUrl() ?>">
                        <span>...</span>
                    </a>
                </li>
            <?php endif;?>

            <?php if ($block->canShowLast()) : ?>
              <li class="item">
                  <a class="page last" href="<?php  echo $block->getLastPageUrl() ?>">
                      <span class="label"><?php  echo __('Page') ?></span>
                      <span><?php  echo $block->getLastPageNum() ?></span>
                  </a>
              </li>
            <?php endif;?>

            <?php if (!$block->isLastPage()) : ?>
                <li class="item pages-item-next">
                    <?php $text = $block->getAnchorTextForNext() ? $block->getAnchorTextForNext() : '';?>
                    <a class="<?php  echo $text ? 'link ' : 'action '?> next" href="<?php  echo $block->getNextPageUrl() ?>" title="<?php  echo $text ? $text : __('Next') ?>">
                        <span class="label"><?php  echo __('Page') ?></span>
                        <span><?php  echo $text ? $text : __('Next') ?></span>
                    </a>
                </li>
            <?php endif;?>
            </ul>
        </div>
        <?php endif; ?>

    <?php if ($block->isShowPerPage()) : ?>
        <div class="limiter">
            <strong class="limiter-label"><?php echo __('Show') ?></strong>
            <select data-mage-init='{"redirectUrl": {"event":"change"}}' class="limiter-options">
                <?php foreach ($block->getAvailableLimit() as $_key => $_limit) : ?>
                    <?php
                    if ($sfrm && $sfrm != $pagersfrm) {
                        $limiterUrl = str_replace('/sfrm/'.$sfrm, '', $block->getLimitUrl($_key));
                        $limiterUrl = str_replace('&amp;sfrm='.$sfrm, '', $limiterUrl);
                        $limiterUrl = str_replace('sfrm='.$sfrm.'&amp;', '', $limiterUrl);
                    } else {
                        $limiterUrl = $block->getLimitUrl($_key);
                    }
                    ?>
                    <option value="<?php  echo $limiterUrl.$limitSfrm; ?>"<?php if ($block->isLimitCurrent($_key)) : ?>
                        selected="s<?php endif ?>>
                        <?php  echo $_limit ?>
                    </option>
                <?php endforeach; ?>
            </select>
            <span class="limiter-text"><?php  echo __('per page') ?></span>
        </div>
    <?php endif ?>

    <?php if ($block->getUseContainer()) : ?>
    </div>
    <?php endif ?>

<?php endif ?>
